// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: JobHistoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_job_history_repository.go -package=mocks goonhub/internal/data JobHistoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockJobHistoryRepository is a mock of JobHistoryRepository interface.
type MockJobHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockJobHistoryRepositoryMockRecorder is the mock recorder for MockJobHistoryRepository.
type MockJobHistoryRepositoryMockRecorder struct {
	mock *MockJobHistoryRepository
}

// NewMockJobHistoryRepository creates a new mock instance.
func NewMockJobHistoryRepository(ctrl *gomock.Controller) *MockJobHistoryRepository {
	mock := &MockJobHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockJobHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobHistoryRepository) EXPECT() *MockJobHistoryRepositoryMockRecorder {
	return m.recorder
}

// ClaimPendingJobs mocks base method.
func (m *MockJobHistoryRepository) ClaimPendingJobs(phase string, limit int) ([]data.JobHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingJobs", phase, limit)
	ret0, _ := ret[0].([]data.JobHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingJobs indicates an expected call of ClaimPendingJobs.
func (mr *MockJobHistoryRepositoryMockRecorder) ClaimPendingJobs(phase, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingJobs", reflect.TypeOf((*MockJobHistoryRepository)(nil).ClaimPendingJobs), phase, limit)
}

// CountPendingByPhase mocks base method.
func (m *MockJobHistoryRepository) CountPendingByPhase() (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByPhase")
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByPhase indicates an expected call of CountPendingByPhase.
func (mr *MockJobHistoryRepositoryMockRecorder) CountPendingByPhase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByPhase", reflect.TypeOf((*MockJobHistoryRepository)(nil).CountPendingByPhase))
}

// Create mocks base method.
func (m *MockJobHistoryRepository) Create(record *data.JobHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobHistoryRepositoryMockRecorder) Create(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobHistoryRepository)(nil).Create), record)
}

// CreateBatch mocks base method.
func (m *MockJobHistoryRepository) CreateBatch(records []*data.JobHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", records)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockJobHistoryRepositoryMockRecorder) CreateBatch(records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockJobHistoryRepository)(nil).CreateBatch), records)
}

// CreatePending mocks base method.
func (m *MockJobHistoryRepository) CreatePending(record *data.JobHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePending", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePending indicates an expected call of CreatePending.
func (mr *MockJobHistoryRepositoryMockRecorder) CreatePending(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePending", reflect.TypeOf((*MockJobHistoryRepository)(nil).CreatePending), record)
}

// DeleteOlderThan mocks base method.
func (m *MockJobHistoryRepository) DeleteOlderThan(before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockJobHistoryRepositoryMockRecorder) DeleteOlderThan(before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockJobHistoryRepository)(nil).DeleteOlderThan), before)
}

// ExistsPendingOrRunning mocks base method.
func (m *MockJobHistoryRepository) ExistsPendingOrRunning(sceneID uint, phase string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsPendingOrRunning", sceneID, phase)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsPendingOrRunning indicates an expected call of ExistsPendingOrRunning.
func (mr *MockJobHistoryRepositoryMockRecorder) ExistsPendingOrRunning(sceneID, phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsPendingOrRunning", reflect.TypeOf((*MockJobHistoryRepository)(nil).ExistsPendingOrRunning), sceneID, phase)
}

// GetByJobID mocks base method.
func (m *MockJobHistoryRepository) GetByJobID(jobID string) (*data.JobHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByJobID", jobID)
	ret0, _ := ret[0].(*data.JobHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByJobID indicates an expected call of GetByJobID.
func (mr *MockJobHistoryRepositoryMockRecorder) GetByJobID(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByJobID", reflect.TypeOf((*MockJobHistoryRepository)(nil).GetByJobID), jobID)
}

// GetRetryableJobs mocks base method.
func (m *MockJobHistoryRepository) GetRetryableJobs() ([]data.JobHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryableJobs")
	ret0, _ := ret[0].([]data.JobHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetryableJobs indicates an expected call of GetRetryableJobs.
func (mr *MockJobHistoryRepositoryMockRecorder) GetRetryableJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryableJobs", reflect.TypeOf((*MockJobHistoryRepository)(nil).GetRetryableJobs))
}

// IncrementRetryCount mocks base method.
func (m *MockJobHistoryRepository) IncrementRetryCount(jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetryCount", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetryCount indicates an expected call of IncrementRetryCount.
func (mr *MockJobHistoryRepositoryMockRecorder) IncrementRetryCount(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetryCount", reflect.TypeOf((*MockJobHistoryRepository)(nil).IncrementRetryCount), jobID)
}

// ListActive mocks base method.
func (m *MockJobHistoryRepository) ListActive() ([]data.JobHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive")
	ret0, _ := ret[0].([]data.JobHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockJobHistoryRepositoryMockRecorder) ListActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockJobHistoryRepository)(nil).ListActive))
}

// ListAll mocks base method.
func (m *MockJobHistoryRepository) ListAll(page, limit int) ([]data.JobHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", page, limit)
	ret0, _ := ret[0].([]data.JobHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAll indicates an expected call of ListAll.
func (mr *MockJobHistoryRepositoryMockRecorder) ListAll(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockJobHistoryRepository)(nil).ListAll), page, limit)
}

// MarkNotRetryable mocks base method.
func (m *MockJobHistoryRepository) MarkNotRetryable(jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotRetryable", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkNotRetryable indicates an expected call of MarkNotRetryable.
func (mr *MockJobHistoryRepositoryMockRecorder) MarkNotRetryable(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotRetryable", reflect.TypeOf((*MockJobHistoryRepository)(nil).MarkNotRetryable), jobID)
}

// MarkOrphanedRunningAsFailed mocks base method.
func (m *MockJobHistoryRepository) MarkOrphanedRunningAsFailed(olderThan time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOrphanedRunningAsFailed", olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOrphanedRunningAsFailed indicates an expected call of MarkOrphanedRunningAsFailed.
func (mr *MockJobHistoryRepositoryMockRecorder) MarkOrphanedRunningAsFailed(olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOrphanedRunningAsFailed", reflect.TypeOf((*MockJobHistoryRepository)(nil).MarkOrphanedRunningAsFailed), olderThan)
}

// MarkRunningAsInterrupted mocks base method.
func (m *MockJobHistoryRepository) MarkRunningAsInterrupted() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRunningAsInterrupted")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRunningAsInterrupted indicates an expected call of MarkRunningAsInterrupted.
func (mr *MockJobHistoryRepositoryMockRecorder) MarkRunningAsInterrupted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRunningAsInterrupted", reflect.TypeOf((*MockJobHistoryRepository)(nil).MarkRunningAsInterrupted))
}

// MarkStuckPendingJobsAsFailed mocks base method.
func (m *MockJobHistoryRepository) MarkStuckPendingJobsAsFailed(olderThan time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkStuckPendingJobsAsFailed", olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkStuckPendingJobsAsFailed indicates an expected call of MarkStuckPendingJobsAsFailed.
func (mr *MockJobHistoryRepositoryMockRecorder) MarkStuckPendingJobsAsFailed(olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkStuckPendingJobsAsFailed", reflect.TypeOf((*MockJobHistoryRepository)(nil).MarkStuckPendingJobsAsFailed), olderThan)
}

// ResetJobsToPending mocks base method.
func (m *MockJobHistoryRepository) ResetJobsToPending(jobIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetJobsToPending", jobIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetJobsToPending indicates an expected call of ResetJobsToPending.
func (mr *MockJobHistoryRepositoryMockRecorder) ResetJobsToPending(jobIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetJobsToPending", reflect.TypeOf((*MockJobHistoryRepository)(nil).ResetJobsToPending), jobIDs)
}

// UpdateProgress mocks base method.
func (m *MockJobHistoryRepository) UpdateProgress(jobID string, progress int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgress", jobID, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockJobHistoryRepositoryMockRecorder) UpdateProgress(jobID, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockJobHistoryRepository)(nil).UpdateProgress), jobID, progress)
}

// UpdateRetryInfo mocks base method.
func (m *MockJobHistoryRepository) UpdateRetryInfo(jobID string, retryCount, maxRetries int, nextRetryAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRetryInfo", jobID, retryCount, maxRetries, nextRetryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRetryInfo indicates an expected call of UpdateRetryInfo.
func (mr *MockJobHistoryRepositoryMockRecorder) UpdateRetryInfo(jobID, retryCount, maxRetries, nextRetryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRetryInfo", reflect.TypeOf((*MockJobHistoryRepository)(nil).UpdateRetryInfo), jobID, retryCount, maxRetries, nextRetryAt)
}

// UpdateStatus mocks base method.
func (m *MockJobHistoryRepository) UpdateStatus(jobID, status string, errorMessage *string, completedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", jobID, status, errorMessage, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockJobHistoryRepositoryMockRecorder) UpdateStatus(jobID, status, errorMessage, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockJobHistoryRepository)(nil).UpdateStatus), jobID, status, errorMessage, completedAt)
}
