// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: DuplicateConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_duplicate_config_repository.go -package=mocks goonhub/internal/data DuplicateConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDuplicateConfigRepository is a mock of DuplicateConfigRepository interface.
type MockDuplicateConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDuplicateConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockDuplicateConfigRepositoryMockRecorder is the mock recorder for MockDuplicateConfigRepository.
type MockDuplicateConfigRepositoryMockRecorder struct {
	mock *MockDuplicateConfigRepository
}

// NewMockDuplicateConfigRepository creates a new mock instance.
func NewMockDuplicateConfigRepository(ctrl *gomock.Controller) *MockDuplicateConfigRepository {
	mock := &MockDuplicateConfigRepository{ctrl: ctrl}
	mock.recorder = &MockDuplicateConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuplicateConfigRepository) EXPECT() *MockDuplicateConfigRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDuplicateConfigRepository) Get() (*data.DuplicateConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*data.DuplicateConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDuplicateConfigRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDuplicateConfigRepository)(nil).Get))
}

// Upsert mocks base method.
func (m *MockDuplicateConfigRepository) Upsert(record *data.DuplicateConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDuplicateConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDuplicateConfigRepository)(nil).Upsert), record)
}
