// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ActorRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_actor_repository.go -package=mocks goonhub/internal/data ActorRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActorRepository is a mock of ActorRepository interface.
type MockActorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepositoryMockRecorder
	isgomock struct{}
}

// MockActorRepositoryMockRecorder is the mock recorder for MockActorRepository.
type MockActorRepositoryMockRecorder struct {
	mock *MockActorRepository
}

// NewMockActorRepository creates a new mock instance.
func NewMockActorRepository(ctrl *gomock.Controller) *MockActorRepository {
	mock := &MockActorRepository{ctrl: ctrl}
	mock.recorder = &MockActorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepository) EXPECT() *MockActorRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActorRepository) Create(actor *data.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActorRepositoryMockRecorder) Create(actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActorRepository)(nil).Create), actor)
}

// Delete mocks base method.
func (m *MockActorRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActorRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActorRepository)(nil).Delete), id)
}

// GetActorVideos mocks base method.
func (m *MockActorRepository) GetActorVideos(actorID uint, page, limit int) ([]data.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorVideos", actorID, page, limit)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActorVideos indicates an expected call of GetActorVideos.
func (mr *MockActorRepositoryMockRecorder) GetActorVideos(actorID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorVideos", reflect.TypeOf((*MockActorRepository)(nil).GetActorVideos), actorID, page, limit)
}

// GetByID mocks base method.
func (m *MockActorRepository) GetByID(id uint) (*data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActorRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActorRepository)(nil).GetByID), id)
}

// GetByUUID mocks base method.
func (m *MockActorRepository) GetByUUID(uuid string) (*data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", uuid)
	ret0, _ := ret[0].(*data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockActorRepositoryMockRecorder) GetByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockActorRepository)(nil).GetByUUID), uuid)
}

// GetVideoActors mocks base method.
func (m *MockActorRepository) GetVideoActors(videoID uint) ([]data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoActors", videoID)
	ret0, _ := ret[0].([]data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoActors indicates an expected call of GetVideoActors.
func (mr *MockActorRepositoryMockRecorder) GetVideoActors(videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoActors", reflect.TypeOf((*MockActorRepository)(nil).GetVideoActors), videoID)
}

// GetVideoCount mocks base method.
func (m *MockActorRepository) GetVideoCount(actorID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoCount", actorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoCount indicates an expected call of GetVideoCount.
func (mr *MockActorRepositoryMockRecorder) GetVideoCount(actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoCount", reflect.TypeOf((*MockActorRepository)(nil).GetVideoCount), actorID)
}

// List mocks base method.
func (m *MockActorRepository) List(page, limit int) ([]data.ActorWithCount, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]data.ActorWithCount)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockActorRepositoryMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActorRepository)(nil).List), page, limit)
}

// Search mocks base method.
func (m *MockActorRepository) Search(query string, page, limit int) ([]data.ActorWithCount, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query, page, limit)
	ret0, _ := ret[0].([]data.ActorWithCount)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockActorRepositoryMockRecorder) Search(query, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockActorRepository)(nil).Search), query, page, limit)
}

// SetVideoActors mocks base method.
func (m *MockActorRepository) SetVideoActors(videoID uint, actorIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVideoActors", videoID, actorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVideoActors indicates an expected call of SetVideoActors.
func (mr *MockActorRepositoryMockRecorder) SetVideoActors(videoID, actorIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVideoActors", reflect.TypeOf((*MockActorRepository)(nil).SetVideoActors), videoID, actorIDs)
}

// Update mocks base method.
func (m *MockActorRepository) Update(actor *data.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockActorRepositoryMockRecorder) Update(actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActorRepository)(nil).Update), actor)
}
