// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ShareLinkRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_share_link_repository.go -package=mocks goonhub/internal/data ShareLinkRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShareLinkRepository is a mock of ShareLinkRepository interface.
type MockShareLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShareLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockShareLinkRepositoryMockRecorder is the mock recorder for MockShareLinkRepository.
type MockShareLinkRepositoryMockRecorder struct {
	mock *MockShareLinkRepository
}

// NewMockShareLinkRepository creates a new mock instance.
func NewMockShareLinkRepository(ctrl *gomock.Controller) *MockShareLinkRepository {
	mock := &MockShareLinkRepository{ctrl: ctrl}
	mock.recorder = &MockShareLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareLinkRepository) EXPECT() *MockShareLinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShareLinkRepository) Create(link *data.ShareLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShareLinkRepositoryMockRecorder) Create(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShareLinkRepository)(nil).Create), link)
}

// Delete mocks base method.
func (m *MockShareLinkRepository) Delete(id, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShareLinkRepositoryMockRecorder) Delete(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShareLinkRepository)(nil).Delete), id, userID)
}

// GetByToken mocks base method.
func (m *MockShareLinkRepository) GetByToken(token string) (*data.ShareLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", token)
	ret0, _ := ret[0].(*data.ShareLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockShareLinkRepositoryMockRecorder) GetByToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockShareLinkRepository)(nil).GetByToken), token)
}

// IncrementViewCount mocks base method.
func (m *MockShareLinkRepository) IncrementViewCount(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementViewCount", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementViewCount indicates an expected call of IncrementViewCount.
func (mr *MockShareLinkRepositoryMockRecorder) IncrementViewCount(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementViewCount", reflect.TypeOf((*MockShareLinkRepository)(nil).IncrementViewCount), id)
}

// ListBySceneAndUser mocks base method.
func (m *MockShareLinkRepository) ListBySceneAndUser(sceneID, userID uint) ([]data.ShareLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySceneAndUser", sceneID, userID)
	ret0, _ := ret[0].([]data.ShareLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySceneAndUser indicates an expected call of ListBySceneAndUser.
func (mr *MockShareLinkRepositoryMockRecorder) ListBySceneAndUser(sceneID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySceneAndUser", reflect.TypeOf((*MockShareLinkRepository)(nil).ListBySceneAndUser), sceneID, userID)
}
