// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ExplorerRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_explorer_repository.go -package=mocks goonhub/internal/data ExplorerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExplorerRepository is a mock of ExplorerRepository interface.
type MockExplorerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExplorerRepositoryMockRecorder
	isgomock struct{}
}

// MockExplorerRepositoryMockRecorder is the mock recorder for MockExplorerRepository.
type MockExplorerRepositoryMockRecorder struct {
	mock *MockExplorerRepository
}

// NewMockExplorerRepository creates a new mock instance.
func NewMockExplorerRepository(ctrl *gomock.Controller) *MockExplorerRepository {
	mock := &MockExplorerRepository{ctrl: ctrl}
	mock.recorder = &MockExplorerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExplorerRepository) EXPECT() *MockExplorerRepositoryMockRecorder {
	return m.recorder
}

// GetStoragePathsWithCounts mocks base method.
func (m *MockExplorerRepository) GetStoragePathsWithCounts() ([]data.StoragePathWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoragePathsWithCounts")
	ret0, _ := ret[0].([]data.StoragePathWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoragePathsWithCounts indicates an expected call of GetStoragePathsWithCounts.
func (mr *MockExplorerRepositoryMockRecorder) GetStoragePathsWithCounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoragePathsWithCounts", reflect.TypeOf((*MockExplorerRepository)(nil).GetStoragePathsWithCounts))
}

// GetSubfolders mocks base method.
func (m *MockExplorerRepository) GetSubfolders(storagePathID uint, parentPath string) ([]data.FolderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubfolders", storagePathID, parentPath)
	ret0, _ := ret[0].([]data.FolderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubfolders indicates an expected call of GetSubfolders.
func (mr *MockExplorerRepositoryMockRecorder) GetSubfolders(storagePathID, parentPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubfolders", reflect.TypeOf((*MockExplorerRepository)(nil).GetSubfolders), storagePathID, parentPath)
}

// GetVideoCountByStoragePath mocks base method.
func (m *MockExplorerRepository) GetVideoCountByStoragePath(storagePathID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoCountByStoragePath", storagePathID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoCountByStoragePath indicates an expected call of GetVideoCountByStoragePath.
func (mr *MockExplorerRepositoryMockRecorder) GetVideoCountByStoragePath(storagePathID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoCountByStoragePath", reflect.TypeOf((*MockExplorerRepository)(nil).GetVideoCountByStoragePath), storagePathID)
}

// GetVideoIDsByFolder mocks base method.
func (m *MockExplorerRepository) GetVideoIDsByFolder(storagePathID uint, folderPath string, recursive bool) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoIDsByFolder", storagePathID, folderPath, recursive)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoIDsByFolder indicates an expected call of GetVideoIDsByFolder.
func (mr *MockExplorerRepositoryMockRecorder) GetVideoIDsByFolder(storagePathID, folderPath, recursive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoIDsByFolder", reflect.TypeOf((*MockExplorerRepository)(nil).GetVideoIDsByFolder), storagePathID, folderPath, recursive)
}

// GetVideosByFolder mocks base method.
func (m *MockExplorerRepository) GetVideosByFolder(storagePathID uint, folderPath string, page, limit int) ([]data.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosByFolder", storagePathID, folderPath, page, limit)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVideosByFolder indicates an expected call of GetVideosByFolder.
func (mr *MockExplorerRepositoryMockRecorder) GetVideosByFolder(storagePathID, folderPath, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosByFolder", reflect.TypeOf((*MockExplorerRepository)(nil).GetVideosByFolder), storagePathID, folderPath, page, limit)
}
