// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: StudioInteractionRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_studio_interaction_repository.go -package=mocks goonhub/internal/data StudioInteractionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStudioInteractionRepository is a mock of StudioInteractionRepository interface.
type MockStudioInteractionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudioInteractionRepositoryMockRecorder
	isgomock struct{}
}

// MockStudioInteractionRepositoryMockRecorder is the mock recorder for MockStudioInteractionRepository.
type MockStudioInteractionRepositoryMockRecorder struct {
	mock *MockStudioInteractionRepository
}

// NewMockStudioInteractionRepository creates a new mock instance.
func NewMockStudioInteractionRepository(ctrl *gomock.Controller) *MockStudioInteractionRepository {
	mock := &MockStudioInteractionRepository{ctrl: ctrl}
	mock.recorder = &MockStudioInteractionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudioInteractionRepository) EXPECT() *MockStudioInteractionRepositoryMockRecorder {
	return m.recorder
}

// DeleteLike mocks base method.
func (m *MockStudioInteractionRepository) DeleteLike(userID, studioID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLike", userID, studioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLike indicates an expected call of DeleteLike.
func (mr *MockStudioInteractionRepositoryMockRecorder) DeleteLike(userID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLike", reflect.TypeOf((*MockStudioInteractionRepository)(nil).DeleteLike), userID, studioID)
}

// DeleteRating mocks base method.
func (m *MockStudioInteractionRepository) DeleteRating(userID, studioID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRating", userID, studioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRating indicates an expected call of DeleteRating.
func (mr *MockStudioInteractionRepositoryMockRecorder) DeleteRating(userID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRating", reflect.TypeOf((*MockStudioInteractionRepository)(nil).DeleteRating), userID, studioID)
}

// GetAllInteractions mocks base method.
func (m *MockStudioInteractionRepository) GetAllInteractions(userID, studioID uint) (*data.StudioInteractions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInteractions", userID, studioID)
	ret0, _ := ret[0].(*data.StudioInteractions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInteractions indicates an expected call of GetAllInteractions.
func (mr *MockStudioInteractionRepositoryMockRecorder) GetAllInteractions(userID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInteractions", reflect.TypeOf((*MockStudioInteractionRepository)(nil).GetAllInteractions), userID, studioID)
}

// GetLikedStudioIDs mocks base method.
func (m *MockStudioInteractionRepository) GetLikedStudioIDs(userID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedStudioIDs", userID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikedStudioIDs indicates an expected call of GetLikedStudioIDs.
func (mr *MockStudioInteractionRepositoryMockRecorder) GetLikedStudioIDs(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedStudioIDs", reflect.TypeOf((*MockStudioInteractionRepository)(nil).GetLikedStudioIDs), userID)
}

// GetRating mocks base method.
func (m *MockStudioInteractionRepository) GetRating(userID, studioID uint) (*data.UserStudioRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", userID, studioID)
	ret0, _ := ret[0].(*data.UserStudioRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockStudioInteractionRepositoryMockRecorder) GetRating(userID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockStudioInteractionRepository)(nil).GetRating), userID, studioID)
}

// IsLiked mocks base method.
func (m *MockStudioInteractionRepository) IsLiked(userID, studioID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", userID, studioID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockStudioInteractionRepositoryMockRecorder) IsLiked(userID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockStudioInteractionRepository)(nil).IsLiked), userID, studioID)
}

// SetLike mocks base method.
func (m *MockStudioInteractionRepository) SetLike(userID, studioID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLike", userID, studioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLike indicates an expected call of SetLike.
func (mr *MockStudioInteractionRepositoryMockRecorder) SetLike(userID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLike", reflect.TypeOf((*MockStudioInteractionRepository)(nil).SetLike), userID, studioID)
}

// UpsertRating mocks base method.
func (m *MockStudioInteractionRepository) UpsertRating(userID, studioID uint, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRating", userID, studioID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRating indicates an expected call of UpsertRating.
func (mr *MockStudioInteractionRepositoryMockRecorder) UpsertRating(userID, studioID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRating", reflect.TypeOf((*MockStudioInteractionRepository)(nil).UpsertRating), userID, studioID, rating)
}
