// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ProcessingConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_processing_config_repository.go -package=mocks goonhub/internal/data ProcessingConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcessingConfigRepository is a mock of ProcessingConfigRepository interface.
type MockProcessingConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcessingConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockProcessingConfigRepositoryMockRecorder is the mock recorder for MockProcessingConfigRepository.
type MockProcessingConfigRepositoryMockRecorder struct {
	mock *MockProcessingConfigRepository
}

// NewMockProcessingConfigRepository creates a new mock instance.
func NewMockProcessingConfigRepository(ctrl *gomock.Controller) *MockProcessingConfigRepository {
	mock := &MockProcessingConfigRepository{ctrl: ctrl}
	mock.recorder = &MockProcessingConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessingConfigRepository) EXPECT() *MockProcessingConfigRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProcessingConfigRepository) Get() (*data.ProcessingConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*data.ProcessingConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProcessingConfigRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProcessingConfigRepository)(nil).Get))
}

// Upsert mocks base method.
func (m *MockProcessingConfigRepository) Upsert(record *data.ProcessingConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProcessingConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProcessingConfigRepository)(nil).Upsert), record)
}
