// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: VideoRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_video_repository.go -package=mocks goonhub/internal/data VideoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockVideoRepository is a mock of VideoRepository interface.
type MockVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockVideoRepositoryMockRecorder is the mock recorder for MockVideoRepository.
type MockVideoRepositoryMockRecorder struct {
	mock *MockVideoRepository
}

// NewMockVideoRepository creates a new mock instance.
func NewMockVideoRepository(ctrl *gomock.Controller) *MockVideoRepository {
	mock := &MockVideoRepository{ctrl: ctrl}
	mock.recorder = &MockVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoRepository) EXPECT() *MockVideoRepositoryMockRecorder {
	return m.recorder
}

// BulkUpdateStudio mocks base method.
func (m *MockVideoRepository) BulkUpdateStudio(videoIDs []uint, studio string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateStudio", videoIDs, studio)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateStudio indicates an expected call of BulkUpdateStudio.
func (mr *MockVideoRepositoryMockRecorder) BulkUpdateStudio(videoIDs, studio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateStudio", reflect.TypeOf((*MockVideoRepository)(nil).BulkUpdateStudio), videoIDs, studio)
}

// Create mocks base method.
func (m *MockVideoRepository) Create(video *data.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVideoRepositoryMockRecorder) Create(video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoRepository)(nil).Create), video)
}

// Delete mocks base method.
func (m *MockVideoRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoRepository)(nil).Delete), id)
}

// ExistsByStoredPath mocks base method.
func (m *MockVideoRepository) ExistsByStoredPath(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByStoredPath", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByStoredPath indicates an expected call of ExistsByStoredPath.
func (mr *MockVideoRepositoryMockRecorder) ExistsByStoredPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByStoredPath", reflect.TypeOf((*MockVideoRepository)(nil).ExistsByStoredPath), path)
}

// GetAll mocks base method.
func (m *MockVideoRepository) GetAll() ([]data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockVideoRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVideoRepository)(nil).GetAll))
}

// GetAllWithStoragePath mocks base method.
func (m *MockVideoRepository) GetAllWithStoragePath() ([]data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithStoragePath")
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithStoragePath indicates an expected call of GetAllWithStoragePath.
func (mr *MockVideoRepositoryMockRecorder) GetAllWithStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithStoragePath", reflect.TypeOf((*MockVideoRepository)(nil).GetAllWithStoragePath))
}

// GetByID mocks base method.
func (m *MockVideoRepository) GetByID(id uint) (*data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVideoRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVideoRepository)(nil).GetByID), id)
}

// GetByIDs mocks base method.
func (m *MockVideoRepository) GetByIDs(ids []uint) ([]data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ids)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockVideoRepositoryMockRecorder) GetByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockVideoRepository)(nil).GetByIDs), ids)
}

// GetBySizeAndFilename mocks base method.
func (m *MockVideoRepository) GetBySizeAndFilename(size int64, filename string) (*data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySizeAndFilename", size, filename)
	ret0, _ := ret[0].(*data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySizeAndFilename indicates an expected call of GetBySizeAndFilename.
func (mr *MockVideoRepositoryMockRecorder) GetBySizeAndFilename(size, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySizeAndFilename", reflect.TypeOf((*MockVideoRepository)(nil).GetBySizeAndFilename), size, filename)
}

// GetDistinctActors mocks base method.
func (m *MockVideoRepository) GetDistinctActors() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctActors")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctActors indicates an expected call of GetDistinctActors.
func (mr *MockVideoRepositoryMockRecorder) GetDistinctActors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctActors", reflect.TypeOf((*MockVideoRepository)(nil).GetDistinctActors))
}

// GetDistinctStudios mocks base method.
func (m *MockVideoRepository) GetDistinctStudios() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctStudios")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctStudios indicates an expected call of GetDistinctStudios.
func (mr *MockVideoRepositoryMockRecorder) GetDistinctStudios() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctStudios", reflect.TypeOf((*MockVideoRepository)(nil).GetDistinctStudios))
}

// GetPendingProcessing mocks base method.
func (m *MockVideoRepository) GetPendingProcessing() ([]data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingProcessing")
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingProcessing indicates an expected call of GetPendingProcessing.
func (mr *MockVideoRepositoryMockRecorder) GetPendingProcessing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingProcessing", reflect.TypeOf((*MockVideoRepository)(nil).GetPendingProcessing))
}

// GetVideosNeedingPhase mocks base method.
func (m *MockVideoRepository) GetVideosNeedingPhase(phase string) ([]data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosNeedingPhase", phase)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideosNeedingPhase indicates an expected call of GetVideosNeedingPhase.
func (mr *MockVideoRepositoryMockRecorder) GetVideosNeedingPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosNeedingPhase", reflect.TypeOf((*MockVideoRepository)(nil).GetVideosNeedingPhase), phase)
}

// List mocks base method.
func (m *MockVideoRepository) List(page, limit int) ([]data.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVideoRepositoryMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVideoRepository)(nil).List), page, limit)
}

// MarkAsMissing mocks base method.
func (m *MockVideoRepository) MarkAsMissing(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsMissing", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsMissing indicates an expected call of MarkAsMissing.
func (mr *MockVideoRepositoryMockRecorder) MarkAsMissing(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsMissing", reflect.TypeOf((*MockVideoRepository)(nil).MarkAsMissing), id)
}

// Restore mocks base method.
func (m *MockVideoRepository) Restore(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockVideoRepositoryMockRecorder) Restore(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockVideoRepository)(nil).Restore), id)
}

// UpdateActors mocks base method.
func (m *MockVideoRepository) UpdateActors(id uint, actors []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActors", id, actors)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActors indicates an expected call of UpdateActors.
func (mr *MockVideoRepositoryMockRecorder) UpdateActors(id, actors any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActors", reflect.TypeOf((*MockVideoRepository)(nil).UpdateActors), id, actors)
}

// UpdateBasicMetadata mocks base method.
func (m *MockVideoRepository) UpdateBasicMetadata(id uint, duration, width, height int, frameRate float64, bitRate int64, videoCodec, audioCodec string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicMetadata", id, duration, width, height, frameRate, bitRate, videoCodec, audioCodec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBasicMetadata indicates an expected call of UpdateBasicMetadata.
func (mr *MockVideoRepositoryMockRecorder) UpdateBasicMetadata(id, duration, width, height, frameRate, bitRate, videoCodec, audioCodec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicMetadata", reflect.TypeOf((*MockVideoRepository)(nil).UpdateBasicMetadata), id, duration, width, height, frameRate, bitRate, videoCodec, audioCodec)
}

// UpdateDetails mocks base method.
func (m *MockVideoRepository) UpdateDetails(id uint, title, description string, releaseDate *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDetails", id, title, description, releaseDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDetails indicates an expected call of UpdateDetails.
func (mr *MockVideoRepositoryMockRecorder) UpdateDetails(id, title, description, releaseDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDetails", reflect.TypeOf((*MockVideoRepository)(nil).UpdateDetails), id, title, description, releaseDate)
}

// UpdateMetadata mocks base method.
func (m *MockVideoRepository) UpdateMetadata(id uint, duration, width, height int, thumbnailPath, spriteSheetPath, vttPath string, spriteSheetCount, thumbnailWidth, thumbnailHeight int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockVideoRepositoryMockRecorder) UpdateMetadata(id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockVideoRepository)(nil).UpdateMetadata), id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight)
}

// UpdateProcessingStatus mocks base method.
func (m *MockVideoRepository) UpdateProcessingStatus(id uint, status, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", id, status, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockVideoRepositoryMockRecorder) UpdateProcessingStatus(id, status, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockVideoRepository)(nil).UpdateProcessingStatus), id, status, errorMsg)
}

// UpdateSceneMetadata mocks base method.
func (m *MockVideoRepository) UpdateSceneMetadata(id uint, title, description, studio string, releaseDate *time.Time, porndbSceneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSceneMetadata", id, title, description, studio, releaseDate, porndbSceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSceneMetadata indicates an expected call of UpdateSceneMetadata.
func (mr *MockVideoRepositoryMockRecorder) UpdateSceneMetadata(id, title, description, studio, releaseDate, porndbSceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSceneMetadata", reflect.TypeOf((*MockVideoRepository)(nil).UpdateSceneMetadata), id, title, description, studio, releaseDate, porndbSceneID)
}

// UpdateSprites mocks base method.
func (m *MockVideoRepository) UpdateSprites(id uint, spriteSheetPath, vttPath string, spriteSheetCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSprites", id, spriteSheetPath, vttPath, spriteSheetCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSprites indicates an expected call of UpdateSprites.
func (mr *MockVideoRepositoryMockRecorder) UpdateSprites(id, spriteSheetPath, vttPath, spriteSheetCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSprites", reflect.TypeOf((*MockVideoRepository)(nil).UpdateSprites), id, spriteSheetPath, vttPath, spriteSheetCount)
}

// UpdateStoredPath mocks base method.
func (m *MockVideoRepository) UpdateStoredPath(id uint, newPath string, storagePathID *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoredPath", id, newPath, storagePathID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStoredPath indicates an expected call of UpdateStoredPath.
func (mr *MockVideoRepositoryMockRecorder) UpdateStoredPath(id, newPath, storagePathID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoredPath", reflect.TypeOf((*MockVideoRepository)(nil).UpdateStoredPath), id, newPath, storagePathID)
}

// UpdateThumbnail mocks base method.
func (m *MockVideoRepository) UpdateThumbnail(id uint, thumbnailPath string, thumbnailWidth, thumbnailHeight int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThumbnail", id, thumbnailPath, thumbnailWidth, thumbnailHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThumbnail indicates an expected call of UpdateThumbnail.
func (mr *MockVideoRepositoryMockRecorder) UpdateThumbnail(id, thumbnailPath, thumbnailWidth, thumbnailHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThumbnail", reflect.TypeOf((*MockVideoRepository)(nil).UpdateThumbnail), id, thumbnailPath, thumbnailWidth, thumbnailHeight)
}
