// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: TagRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_tag_repository.go -package=mocks goonhub/internal/data TagRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagRepository) Create(tag *data.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), tag)
}

// Delete mocks base method.
func (m *MockTagRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockTagRepository) GetByID(id uint) (*data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTagRepository)(nil).GetByID), id)
}

// GetVideoTags mocks base method.
func (m *MockTagRepository) GetVideoTags(videoID uint) ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoTags", videoID)
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoTags indicates an expected call of GetVideoTags.
func (mr *MockTagRepositoryMockRecorder) GetVideoTags(videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoTags", reflect.TypeOf((*MockTagRepository)(nil).GetVideoTags), videoID)
}

// List mocks base method.
func (m *MockTagRepository) List() ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagRepository)(nil).List))
}

// ListWithCounts mocks base method.
func (m *MockTagRepository) ListWithCounts() ([]data.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithCounts")
	ret0, _ := ret[0].([]data.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithCounts indicates an expected call of ListWithCounts.
func (mr *MockTagRepositoryMockRecorder) ListWithCounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithCounts", reflect.TypeOf((*MockTagRepository)(nil).ListWithCounts))
}

// SetVideoTags mocks base method.
func (m *MockTagRepository) SetVideoTags(videoID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVideoTags", videoID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVideoTags indicates an expected call of SetVideoTags.
func (mr *MockTagRepositoryMockRecorder) SetVideoTags(videoID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVideoTags", reflect.TypeOf((*MockTagRepository)(nil).SetVideoTags), videoID, tagIDs)
}
