// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ExplorerRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_explorer_repository.go -package=mocks goonhub/internal/data ExplorerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExplorerRepository is a mock of ExplorerRepository interface.
type MockExplorerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExplorerRepositoryMockRecorder
	isgomock struct{}
}

// MockExplorerRepositoryMockRecorder is the mock recorder for MockExplorerRepository.
type MockExplorerRepositoryMockRecorder struct {
	mock *MockExplorerRepository
}

// NewMockExplorerRepository creates a new mock instance.
func NewMockExplorerRepository(ctrl *gomock.Controller) *MockExplorerRepository {
	mock := &MockExplorerRepository{ctrl: ctrl}
	mock.recorder = &MockExplorerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExplorerRepository) EXPECT() *MockExplorerRepositoryMockRecorder {
	return m.recorder
}

// GetSceneCountByStoragePath mocks base method.
func (m *MockExplorerRepository) GetSceneCountByStoragePath(storagePathID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneCountByStoragePath", storagePathID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneCountByStoragePath indicates an expected call of GetSceneCountByStoragePath.
func (mr *MockExplorerRepositoryMockRecorder) GetSceneCountByStoragePath(storagePathID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneCountByStoragePath", reflect.TypeOf((*MockExplorerRepository)(nil).GetSceneCountByStoragePath), storagePathID)
}

// GetSceneIDsByFolder mocks base method.
func (m *MockExplorerRepository) GetSceneIDsByFolder(storagePathID uint, folderPath string, recursive bool) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneIDsByFolder", storagePathID, folderPath, recursive)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneIDsByFolder indicates an expected call of GetSceneIDsByFolder.
func (mr *MockExplorerRepositoryMockRecorder) GetSceneIDsByFolder(storagePathID, folderPath, recursive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneIDsByFolder", reflect.TypeOf((*MockExplorerRepository)(nil).GetSceneIDsByFolder), storagePathID, folderPath, recursive)
}

// GetScenesByFolder mocks base method.
func (m *MockExplorerRepository) GetScenesByFolder(storagePathID uint, folderPath string, page, limit int) ([]data.Scene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenesByFolder", storagePathID, folderPath, page, limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetScenesByFolder indicates an expected call of GetScenesByFolder.
func (mr *MockExplorerRepositoryMockRecorder) GetScenesByFolder(storagePathID, folderPath, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenesByFolder", reflect.TypeOf((*MockExplorerRepository)(nil).GetScenesByFolder), storagePathID, folderPath, page, limit)
}

// GetStoragePathsWithCounts mocks base method.
func (m *MockExplorerRepository) GetStoragePathsWithCounts() ([]data.StoragePathWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoragePathsWithCounts")
	ret0, _ := ret[0].([]data.StoragePathWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoragePathsWithCounts indicates an expected call of GetStoragePathsWithCounts.
func (mr *MockExplorerRepositoryMockRecorder) GetStoragePathsWithCounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoragePathsWithCounts", reflect.TypeOf((*MockExplorerRepository)(nil).GetStoragePathsWithCounts))
}

// GetSubfolders mocks base method.
func (m *MockExplorerRepository) GetSubfolders(storagePathID uint, parentPath string) ([]data.FolderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubfolders", storagePathID, parentPath)
	ret0, _ := ret[0].([]data.FolderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubfolders indicates an expected call of GetSubfolders.
func (mr *MockExplorerRepositoryMockRecorder) GetSubfolders(storagePathID, parentPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubfolders", reflect.TypeOf((*MockExplorerRepository)(nil).GetSubfolders), storagePathID, parentPath)
}
