// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: RetryConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_retry_config_repository.go -package=mocks goonhub/internal/data RetryConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRetryConfigRepository is a mock of RetryConfigRepository interface.
type MockRetryConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRetryConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockRetryConfigRepositoryMockRecorder is the mock recorder for MockRetryConfigRepository.
type MockRetryConfigRepositoryMockRecorder struct {
	mock *MockRetryConfigRepository
}

// NewMockRetryConfigRepository creates a new mock instance.
func NewMockRetryConfigRepository(ctrl *gomock.Controller) *MockRetryConfigRepository {
	mock := &MockRetryConfigRepository{ctrl: ctrl}
	mock.recorder = &MockRetryConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetryConfigRepository) EXPECT() *MockRetryConfigRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockRetryConfigRepository) GetAll() ([]data.RetryConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]data.RetryConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRetryConfigRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRetryConfigRepository)(nil).GetAll))
}

// GetByPhase mocks base method.
func (m *MockRetryConfigRepository) GetByPhase(phase string) (*data.RetryConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhase", phase)
	ret0, _ := ret[0].(*data.RetryConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhase indicates an expected call of GetByPhase.
func (mr *MockRetryConfigRepositoryMockRecorder) GetByPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhase", reflect.TypeOf((*MockRetryConfigRepository)(nil).GetByPhase), phase)
}

// Upsert mocks base method.
func (m *MockRetryConfigRepository) Upsert(record *data.RetryConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRetryConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRetryConfigRepository)(nil).Upsert), record)
}
