// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: StudioRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_studio_repository.go -package=mocks goonhub/internal/data StudioRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStudioRepository is a mock of StudioRepository interface.
type MockStudioRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudioRepositoryMockRecorder
	isgomock struct{}
}

// MockStudioRepositoryMockRecorder is the mock recorder for MockStudioRepository.
type MockStudioRepositoryMockRecorder struct {
	mock *MockStudioRepository
}

// NewMockStudioRepository creates a new mock instance.
func NewMockStudioRepository(ctrl *gomock.Controller) *MockStudioRepository {
	mock := &MockStudioRepository{ctrl: ctrl}
	mock.recorder = &MockStudioRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudioRepository) EXPECT() *MockStudioRepositoryMockRecorder {
	return m.recorder
}

// BulkSetStudioForVideos mocks base method.
func (m *MockStudioRepository) BulkSetStudioForVideos(videoIDs []uint, studioID *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSetStudioForVideos", videoIDs, studioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkSetStudioForVideos indicates an expected call of BulkSetStudioForVideos.
func (mr *MockStudioRepositoryMockRecorder) BulkSetStudioForVideos(videoIDs, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSetStudioForVideos", reflect.TypeOf((*MockStudioRepository)(nil).BulkSetStudioForVideos), videoIDs, studioID)
}

// Create mocks base method.
func (m *MockStudioRepository) Create(studio *data.Studio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", studio)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStudioRepositoryMockRecorder) Create(studio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudioRepository)(nil).Create), studio)
}

// Delete mocks base method.
func (m *MockStudioRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStudioRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStudioRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockStudioRepository) GetByID(id uint) (*data.Studio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Studio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStudioRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStudioRepository)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockStudioRepository) GetByName(name string) (*data.Studio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*data.Studio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockStudioRepositoryMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockStudioRepository)(nil).GetByName), name)
}

// GetByUUID mocks base method.
func (m *MockStudioRepository) GetByUUID(uuid string) (*data.Studio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", uuid)
	ret0, _ := ret[0].(*data.Studio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockStudioRepositoryMockRecorder) GetByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockStudioRepository)(nil).GetByUUID), uuid)
}

// GetStudioVideos mocks base method.
func (m *MockStudioRepository) GetStudioVideos(studioID uint, page, limit int) ([]data.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudioVideos", studioID, page, limit)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStudioVideos indicates an expected call of GetStudioVideos.
func (mr *MockStudioRepositoryMockRecorder) GetStudioVideos(studioID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudioVideos", reflect.TypeOf((*MockStudioRepository)(nil).GetStudioVideos), studioID, page, limit)
}

// GetVideoCount mocks base method.
func (m *MockStudioRepository) GetVideoCount(studioID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoCount", studioID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoCount indicates an expected call of GetVideoCount.
func (mr *MockStudioRepositoryMockRecorder) GetVideoCount(studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoCount", reflect.TypeOf((*MockStudioRepository)(nil).GetVideoCount), studioID)
}

// GetVideoStudio mocks base method.
func (m *MockStudioRepository) GetVideoStudio(videoID uint) (*data.Studio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoStudio", videoID)
	ret0, _ := ret[0].(*data.Studio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoStudio indicates an expected call of GetVideoStudio.
func (mr *MockStudioRepositoryMockRecorder) GetVideoStudio(videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoStudio", reflect.TypeOf((*MockStudioRepository)(nil).GetVideoStudio), videoID)
}

// List mocks base method.
func (m *MockStudioRepository) List(page, limit int) ([]data.StudioWithCount, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]data.StudioWithCount)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStudioRepositoryMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStudioRepository)(nil).List), page, limit)
}

// Search mocks base method.
func (m *MockStudioRepository) Search(query string, page, limit int) ([]data.StudioWithCount, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query, page, limit)
	ret0, _ := ret[0].([]data.StudioWithCount)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockStudioRepositoryMockRecorder) Search(query, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockStudioRepository)(nil).Search), query, page, limit)
}

// SetVideoStudio mocks base method.
func (m *MockStudioRepository) SetVideoStudio(videoID uint, studioID *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVideoStudio", videoID, studioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVideoStudio indicates an expected call of SetVideoStudio.
func (mr *MockStudioRepositoryMockRecorder) SetVideoStudio(videoID, studioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVideoStudio", reflect.TypeOf((*MockStudioRepository)(nil).SetVideoStudio), videoID, studioID)
}

// Update mocks base method.
func (m *MockStudioRepository) Update(studio *data.Studio) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", studio)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudioRepositoryMockRecorder) Update(studio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudioRepository)(nil).Update), studio)
}
