// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: DuplicateGroupRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_duplicate_group_repository.go -package=mocks goonhub/internal/data DuplicateGroupRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDuplicateGroupRepository is a mock of DuplicateGroupRepository interface.
type MockDuplicateGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDuplicateGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockDuplicateGroupRepositoryMockRecorder is the mock recorder for MockDuplicateGroupRepository.
type MockDuplicateGroupRepositoryMockRecorder struct {
	mock *MockDuplicateGroupRepository
}

// NewMockDuplicateGroupRepository creates a new mock instance.
func NewMockDuplicateGroupRepository(ctrl *gomock.Controller) *MockDuplicateGroupRepository {
	mock := &MockDuplicateGroupRepository{ctrl: ctrl}
	mock.recorder = &MockDuplicateGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuplicateGroupRepository) EXPECT() *MockDuplicateGroupRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockDuplicateGroupRepository) AddMember(member *data.DuplicateGroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockDuplicateGroupRepositoryMockRecorder) AddMember(member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).AddMember), member)
}

// CountByStatus mocks base method.
func (m *MockDuplicateGroupRepository) CountByStatus() (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus")
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockDuplicateGroupRepositoryMockRecorder) CountByStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).CountByStatus))
}

// Create mocks base method.
func (m *MockDuplicateGroupRepository) Create(group *data.DuplicateGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDuplicateGroupRepositoryMockRecorder) Create(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).Create), group)
}

// Delete mocks base method.
func (m *MockDuplicateGroupRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDuplicateGroupRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockDuplicateGroupRepository) GetByID(id uint) (*data.DuplicateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.DuplicateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDuplicateGroupRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).GetByID), id)
}

// GetByIDWithMembers mocks base method.
func (m *MockDuplicateGroupRepository) GetByIDWithMembers(id uint) (*data.DuplicateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithMembers", id)
	ret0, _ := ret[0].(*data.DuplicateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithMembers indicates an expected call of GetByIDWithMembers.
func (mr *MockDuplicateGroupRepositoryMockRecorder) GetByIDWithMembers(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithMembers", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).GetByIDWithMembers), id)
}

// GetGroupBySceneID mocks base method.
func (m *MockDuplicateGroupRepository) GetGroupBySceneID(sceneID uint) (*data.DuplicateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupBySceneID", sceneID)
	ret0, _ := ret[0].(*data.DuplicateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupBySceneID indicates an expected call of GetGroupBySceneID.
func (mr *MockDuplicateGroupRepositoryMockRecorder) GetGroupBySceneID(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupBySceneID", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).GetGroupBySceneID), sceneID)
}

// GetGroupsBySceneIDs mocks base method.
func (m *MockDuplicateGroupRepository) GetGroupsBySceneIDs(sceneIDs []uint) (map[uint]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsBySceneIDs", sceneIDs)
	ret0, _ := ret[0].(map[uint]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsBySceneIDs indicates an expected call of GetGroupsBySceneIDs.
func (mr *MockDuplicateGroupRepositoryMockRecorder) GetGroupsBySceneIDs(sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsBySceneIDs", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).GetGroupsBySceneIDs), sceneIDs)
}

// List mocks base method.
func (m *MockDuplicateGroupRepository) List(page, limit int, status string) ([]data.DuplicateGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit, status)
	ret0, _ := ret[0].([]data.DuplicateGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDuplicateGroupRepositoryMockRecorder) List(page, limit, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).List), page, limit, status)
}

// ListWithMembers mocks base method.
func (m *MockDuplicateGroupRepository) ListWithMembers(page, limit int, status string) ([]data.DuplicateGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithMembers", page, limit, status)
	ret0, _ := ret[0].([]data.DuplicateGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithMembers indicates an expected call of ListWithMembers.
func (mr *MockDuplicateGroupRepositoryMockRecorder) ListWithMembers(page, limit, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithMembers", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).ListWithMembers), page, limit, status)
}

// MergeGroups mocks base method.
func (m *MockDuplicateGroupRepository) MergeGroups(targetID uint, sourceIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeGroups", targetID, sourceIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeGroups indicates an expected call of MergeGroups.
func (mr *MockDuplicateGroupRepositoryMockRecorder) MergeGroups(targetID, sourceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeGroups", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).MergeGroups), targetID, sourceIDs)
}

// RemoveMember mocks base method.
func (m *MockDuplicateGroupRepository) RemoveMember(groupID, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", groupID, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockDuplicateGroupRepositoryMockRecorder) RemoveMember(groupID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).RemoveMember), groupID, sceneID)
}

// RunInTransaction mocks base method.
func (m *MockDuplicateGroupRepository) RunInTransaction(fn func(data.DuplicateGroupRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTransaction", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTransaction indicates an expected call of RunInTransaction.
func (mr *MockDuplicateGroupRepositoryMockRecorder) RunInTransaction(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTransaction", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).RunInTransaction), fn)
}

// SetBestScene mocks base method.
func (m *MockDuplicateGroupRepository) SetBestScene(id, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBestScene", id, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBestScene indicates an expected call of SetBestScene.
func (mr *MockDuplicateGroupRepositoryMockRecorder) SetBestScene(id, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBestScene", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).SetBestScene), id, sceneID)
}

// UpdateMemberBest mocks base method.
func (m *MockDuplicateGroupRepository) UpdateMemberBest(groupID, sceneID uint, isBest bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberBest", groupID, sceneID, isBest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberBest indicates an expected call of UpdateMemberBest.
func (mr *MockDuplicateGroupRepositoryMockRecorder) UpdateMemberBest(groupID, sceneID, isBest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberBest", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).UpdateMemberBest), groupID, sceneID, isBest)
}

// UpdateSceneCount mocks base method.
func (m *MockDuplicateGroupRepository) UpdateSceneCount(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSceneCount", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSceneCount indicates an expected call of UpdateSceneCount.
func (mr *MockDuplicateGroupRepositoryMockRecorder) UpdateSceneCount(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSceneCount", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).UpdateSceneCount), id)
}

// UpdateStatus mocks base method.
func (m *MockDuplicateGroupRepository) UpdateStatus(id uint, status string, resolvedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status, resolvedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDuplicateGroupRepositoryMockRecorder) UpdateStatus(id, status, resolvedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDuplicateGroupRepository)(nil).UpdateStatus), id, status, resolvedAt)
}
