// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: JobHistoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_job_history_repository.go -package=mocks goonhub/internal/data JobHistoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockJobHistoryRepository is a mock of JobHistoryRepository interface.
type MockJobHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockJobHistoryRepositoryMockRecorder is the mock recorder for MockJobHistoryRepository.
type MockJobHistoryRepositoryMockRecorder struct {
	mock *MockJobHistoryRepository
}

// NewMockJobHistoryRepository creates a new mock instance.
func NewMockJobHistoryRepository(ctrl *gomock.Controller) *MockJobHistoryRepository {
	mock := &MockJobHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockJobHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobHistoryRepository) EXPECT() *MockJobHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobHistoryRepository) Create(record *data.JobHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobHistoryRepositoryMockRecorder) Create(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobHistoryRepository)(nil).Create), record)
}

// DeleteOlderThan mocks base method.
func (m *MockJobHistoryRepository) DeleteOlderThan(before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockJobHistoryRepositoryMockRecorder) DeleteOlderThan(before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockJobHistoryRepository)(nil).DeleteOlderThan), before)
}

// ListActive mocks base method.
func (m *MockJobHistoryRepository) ListActive() ([]data.JobHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive")
	ret0, _ := ret[0].([]data.JobHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockJobHistoryRepositoryMockRecorder) ListActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockJobHistoryRepository)(nil).ListActive))
}

// ListAll mocks base method.
func (m *MockJobHistoryRepository) ListAll(page, limit int) ([]data.JobHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", page, limit)
	ret0, _ := ret[0].([]data.JobHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAll indicates an expected call of ListAll.
func (mr *MockJobHistoryRepositoryMockRecorder) ListAll(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockJobHistoryRepository)(nil).ListAll), page, limit)
}

// UpdateStatus mocks base method.
func (m *MockJobHistoryRepository) UpdateStatus(jobID, status string, errorMessage *string, completedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", jobID, status, errorMessage, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockJobHistoryRepositoryMockRecorder) UpdateStatus(jobID, status, errorMessage, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockJobHistoryRepository)(nil).UpdateStatus), jobID, status, errorMessage, completedAt)
}
