// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: DuplicationConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_duplication_config_repository.go -package=mocks goonhub/internal/data DuplicationConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDuplicationConfigRepository is a mock of DuplicationConfigRepository interface.
type MockDuplicationConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDuplicationConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockDuplicationConfigRepositoryMockRecorder is the mock recorder for MockDuplicationConfigRepository.
type MockDuplicationConfigRepositoryMockRecorder struct {
	mock *MockDuplicationConfigRepository
}

// NewMockDuplicationConfigRepository creates a new mock instance.
func NewMockDuplicationConfigRepository(ctrl *gomock.Controller) *MockDuplicationConfigRepository {
	mock := &MockDuplicationConfigRepository{ctrl: ctrl}
	mock.recorder = &MockDuplicationConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuplicationConfigRepository) EXPECT() *MockDuplicationConfigRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDuplicationConfigRepository) Get() (*data.DuplicationConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*data.DuplicationConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDuplicationConfigRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDuplicationConfigRepository)(nil).Get))
}

// Upsert mocks base method.
func (m *MockDuplicationConfigRepository) Upsert(record *data.DuplicationConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDuplicationConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDuplicationConfigRepository)(nil).Upsert), record)
}
