// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: InteractionRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_interaction_repository.go -package=mocks goonhub/internal/data InteractionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractionRepository is a mock of InteractionRepository interface.
type MockInteractionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionRepositoryMockRecorder
	isgomock struct{}
}

// MockInteractionRepositoryMockRecorder is the mock recorder for MockInteractionRepository.
type MockInteractionRepositoryMockRecorder struct {
	mock *MockInteractionRepository
}

// NewMockInteractionRepository creates a new mock instance.
func NewMockInteractionRepository(ctrl *gomock.Controller) *MockInteractionRepository {
	mock := &MockInteractionRepository{ctrl: ctrl}
	mock.recorder = &MockInteractionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionRepository) EXPECT() *MockInteractionRepositoryMockRecorder {
	return m.recorder
}

// DeleteLike mocks base method.
func (m *MockInteractionRepository) DeleteLike(userID, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLike", userID, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLike indicates an expected call of DeleteLike.
func (mr *MockInteractionRepositoryMockRecorder) DeleteLike(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLike", reflect.TypeOf((*MockInteractionRepository)(nil).DeleteLike), userID, sceneID)
}

// DeleteRating mocks base method.
func (m *MockInteractionRepository) DeleteRating(userID, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRating", userID, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRating indicates an expected call of DeleteRating.
func (mr *MockInteractionRepositoryMockRecorder) DeleteRating(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRating", reflect.TypeOf((*MockInteractionRepository)(nil).DeleteRating), userID, sceneID)
}

// GetAllInteractions mocks base method.
func (m *MockInteractionRepository) GetAllInteractions(userID, sceneID uint) (*data.SceneInteractions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInteractions", userID, sceneID)
	ret0, _ := ret[0].(*data.SceneInteractions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInteractions indicates an expected call of GetAllInteractions.
func (mr *MockInteractionRepositoryMockRecorder) GetAllInteractions(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInteractions", reflect.TypeOf((*MockInteractionRepository)(nil).GetAllInteractions), userID, sceneID)
}

// GetJizzCountsBySceneIDs mocks base method.
func (m *MockInteractionRepository) GetJizzCountsBySceneIDs(userID uint, sceneIDs []uint) (map[uint]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJizzCountsBySceneIDs", userID, sceneIDs)
	ret0, _ := ret[0].(map[uint]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJizzCountsBySceneIDs indicates an expected call of GetJizzCountsBySceneIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetJizzCountsBySceneIDs(userID, sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJizzCountsBySceneIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetJizzCountsBySceneIDs), userID, sceneIDs)
}

// GetJizzedCount mocks base method.
func (m *MockInteractionRepository) GetJizzedCount(userID, sceneID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJizzedCount", userID, sceneID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJizzedCount indicates an expected call of GetJizzedCount.
func (mr *MockInteractionRepositoryMockRecorder) GetJizzedCount(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJizzedCount", reflect.TypeOf((*MockInteractionRepository)(nil).GetJizzedCount), userID, sceneID)
}

// GetJizzedSceneIDs mocks base method.
func (m *MockInteractionRepository) GetJizzedSceneIDs(userID uint, minCount, maxCount int) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJizzedSceneIDs", userID, minCount, maxCount)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJizzedSceneIDs indicates an expected call of GetJizzedSceneIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetJizzedSceneIDs(userID, minCount, maxCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJizzedSceneIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetJizzedSceneIDs), userID, minCount, maxCount)
}

// GetLikedSceneIDs mocks base method.
func (m *MockInteractionRepository) GetLikedSceneIDs(userID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedSceneIDs", userID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikedSceneIDs indicates an expected call of GetLikedSceneIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetLikedSceneIDs(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedSceneIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetLikedSceneIDs), userID)
}

// GetLikesBySceneIDs mocks base method.
func (m *MockInteractionRepository) GetLikesBySceneIDs(userID uint, sceneIDs []uint) (map[uint]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesBySceneIDs", userID, sceneIDs)
	ret0, _ := ret[0].(map[uint]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikesBySceneIDs indicates an expected call of GetLikesBySceneIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetLikesBySceneIDs(userID, sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesBySceneIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetLikesBySceneIDs), userID, sceneIDs)
}

// GetRatedSceneIDs mocks base method.
func (m *MockInteractionRepository) GetRatedSceneIDs(userID uint, minRating, maxRating float64) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatedSceneIDs", userID, minRating, maxRating)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatedSceneIDs indicates an expected call of GetRatedSceneIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetRatedSceneIDs(userID, minRating, maxRating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatedSceneIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetRatedSceneIDs), userID, minRating, maxRating)
}

// GetRating mocks base method.
func (m *MockInteractionRepository) GetRating(userID, sceneID uint) (*data.UserSceneRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", userID, sceneID)
	ret0, _ := ret[0].(*data.UserSceneRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockInteractionRepositoryMockRecorder) GetRating(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockInteractionRepository)(nil).GetRating), userID, sceneID)
}

// GetRatingsBySceneIDs mocks base method.
func (m *MockInteractionRepository) GetRatingsBySceneIDs(userID uint, sceneIDs []uint) (map[uint]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatingsBySceneIDs", userID, sceneIDs)
	ret0, _ := ret[0].(map[uint]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatingsBySceneIDs indicates an expected call of GetRatingsBySceneIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetRatingsBySceneIDs(userID, sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatingsBySceneIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetRatingsBySceneIDs), userID, sceneIDs)
}

// IncrementJizzed mocks base method.
func (m *MockInteractionRepository) IncrementJizzed(userID, sceneID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementJizzed", userID, sceneID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementJizzed indicates an expected call of IncrementJizzed.
func (mr *MockInteractionRepositoryMockRecorder) IncrementJizzed(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementJizzed", reflect.TypeOf((*MockInteractionRepository)(nil).IncrementJizzed), userID, sceneID)
}

// IsLiked mocks base method.
func (m *MockInteractionRepository) IsLiked(userID, sceneID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", userID, sceneID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockInteractionRepositoryMockRecorder) IsLiked(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockInteractionRepository)(nil).IsLiked), userID, sceneID)
}

// ReassignInteractionsToScene mocks base method.
func (m *MockInteractionRepository) ReassignInteractionsToScene(fromSceneID, toSceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignInteractionsToScene", fromSceneID, toSceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignInteractionsToScene indicates an expected call of ReassignInteractionsToScene.
func (mr *MockInteractionRepositoryMockRecorder) ReassignInteractionsToScene(fromSceneID, toSceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignInteractionsToScene", reflect.TypeOf((*MockInteractionRepository)(nil).ReassignInteractionsToScene), fromSceneID, toSceneID)
}

// SetLike mocks base method.
func (m *MockInteractionRepository) SetLike(userID, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLike", userID, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLike indicates an expected call of SetLike.
func (mr *MockInteractionRepositoryMockRecorder) SetLike(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLike", reflect.TypeOf((*MockInteractionRepository)(nil).SetLike), userID, sceneID)
}

// UpsertRating mocks base method.
func (m *MockInteractionRepository) UpsertRating(userID, sceneID uint, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRating", userID, sceneID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRating indicates an expected call of UpsertRating.
func (mr *MockInteractionRepositoryMockRecorder) UpsertRating(userID, sceneID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRating", reflect.TypeOf((*MockInteractionRepository)(nil).UpsertRating), userID, sceneID, rating)
}
