// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: WatchHistoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_watch_history_repository.go -package=mocks goonhub/internal/data WatchHistoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockWatchHistoryRepository is a mock of WatchHistoryRepository interface.
type MockWatchHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWatchHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockWatchHistoryRepositoryMockRecorder is the mock recorder for MockWatchHistoryRepository.
type MockWatchHistoryRepositoryMockRecorder struct {
	mock *MockWatchHistoryRepository
}

// NewMockWatchHistoryRepository creates a new mock instance.
func NewMockWatchHistoryRepository(ctrl *gomock.Controller) *MockWatchHistoryRepository {
	mock := &MockWatchHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockWatchHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchHistoryRepository) EXPECT() *MockWatchHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetDailyActivityCounts mocks base method.
func (m *MockWatchHistoryRepository) GetDailyActivityCounts(userID uint, since time.Time) ([]data.DailyActivityCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyActivityCounts", userID, since)
	ret0, _ := ret[0].([]data.DailyActivityCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyActivityCounts indicates an expected call of GetDailyActivityCounts.
func (mr *MockWatchHistoryRepositoryMockRecorder) GetDailyActivityCounts(userID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyActivityCounts", reflect.TypeOf((*MockWatchHistoryRepository)(nil).GetDailyActivityCounts), userID, since)
}

// GetLastWatch mocks base method.
func (m *MockWatchHistoryRepository) GetLastWatch(userID, sceneID uint) (*data.UserSceneWatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastWatch", userID, sceneID)
	ret0, _ := ret[0].(*data.UserSceneWatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastWatch indicates an expected call of GetLastWatch.
func (mr *MockWatchHistoryRepositoryMockRecorder) GetLastWatch(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastWatch", reflect.TypeOf((*MockWatchHistoryRepository)(nil).GetLastWatch), userID, sceneID)
}

// ListSceneWatches mocks base method.
func (m *MockWatchHistoryRepository) ListSceneWatches(userID, sceneID uint, limit int) ([]data.UserSceneWatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSceneWatches", userID, sceneID, limit)
	ret0, _ := ret[0].([]data.UserSceneWatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSceneWatches indicates an expected call of ListSceneWatches.
func (mr *MockWatchHistoryRepositoryMockRecorder) ListSceneWatches(userID, sceneID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSceneWatches", reflect.TypeOf((*MockWatchHistoryRepository)(nil).ListSceneWatches), userID, sceneID, limit)
}

// ListUserHistory mocks base method.
func (m *MockWatchHistoryRepository) ListUserHistory(userID uint, page, limit int) ([]data.UserSceneWatch, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserHistory", userID, page, limit)
	ret0, _ := ret[0].([]data.UserSceneWatch)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserHistory indicates an expected call of ListUserHistory.
func (mr *MockWatchHistoryRepositoryMockRecorder) ListUserHistory(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserHistory", reflect.TypeOf((*MockWatchHistoryRepository)(nil).ListUserHistory), userID, page, limit)
}

// ListUserHistoryByDateRange mocks base method.
func (m *MockWatchHistoryRepository) ListUserHistoryByDateRange(userID uint, since time.Time, limit int) ([]data.UserSceneWatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserHistoryByDateRange", userID, since, limit)
	ret0, _ := ret[0].([]data.UserSceneWatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserHistoryByDateRange indicates an expected call of ListUserHistoryByDateRange.
func (mr *MockWatchHistoryRepositoryMockRecorder) ListUserHistoryByDateRange(userID, since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserHistoryByDateRange", reflect.TypeOf((*MockWatchHistoryRepository)(nil).ListUserHistoryByDateRange), userID, since, limit)
}

// RecordWatch mocks base method.
func (m *MockWatchHistoryRepository) RecordWatch(userID, sceneID uint, duration, position int, completed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordWatch", userID, sceneID, duration, position, completed)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordWatch indicates an expected call of RecordWatch.
func (mr *MockWatchHistoryRepositoryMockRecorder) RecordWatch(userID, sceneID, duration, position, completed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordWatch", reflect.TypeOf((*MockWatchHistoryRepository)(nil).RecordWatch), userID, sceneID, duration, position, completed)
}

// TryIncrementViewCount mocks base method.
func (m *MockWatchHistoryRepository) TryIncrementViewCount(userID, sceneID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryIncrementViewCount", userID, sceneID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryIncrementViewCount indicates an expected call of TryIncrementViewCount.
func (mr *MockWatchHistoryRepositoryMockRecorder) TryIncrementViewCount(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryIncrementViewCount", reflect.TypeOf((*MockWatchHistoryRepository)(nil).TryIncrementViewCount), userID, sceneID)
}
