// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: UserSettingsRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_user_settings_repository.go -package=mocks goonhub/internal/data UserSettingsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserSettingsRepository is a mock of UserSettingsRepository interface.
type MockUserSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockUserSettingsRepositoryMockRecorder is the mock recorder for MockUserSettingsRepository.
type MockUserSettingsRepositoryMockRecorder struct {
	mock *MockUserSettingsRepository
}

// NewMockUserSettingsRepository creates a new mock instance.
func NewMockUserSettingsRepository(ctrl *gomock.Controller) *MockUserSettingsRepository {
	mock := &MockUserSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockUserSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsRepository) EXPECT() *MockUserSettingsRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockUserSettingsRepository) GetByUserID(userID uint) (*data.UserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*data.UserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserSettingsRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserSettingsRepository)(nil).GetByUserID), userID)
}

// Upsert mocks base method.
func (m *MockUserSettingsRepository) Upsert(settings *data.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserSettingsRepositoryMockRecorder) Upsert(settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserSettingsRepository)(nil).Upsert), settings)
}
