// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: PlaylistRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_playlist_repository.go -package=mocks goonhub/internal/data PlaylistRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlaylistRepository is a mock of PlaylistRepository interface.
type MockPlaylistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlaylistRepositoryMockRecorder
	isgomock struct{}
}

// MockPlaylistRepositoryMockRecorder is the mock recorder for MockPlaylistRepository.
type MockPlaylistRepositoryMockRecorder struct {
	mock *MockPlaylistRepository
}

// NewMockPlaylistRepository creates a new mock instance.
func NewMockPlaylistRepository(ctrl *gomock.Controller) *MockPlaylistRepository {
	mock := &MockPlaylistRepository{ctrl: ctrl}
	mock.recorder = &MockPlaylistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaylistRepository) EXPECT() *MockPlaylistRepositoryMockRecorder {
	return m.recorder
}

// AddScenes mocks base method.
func (m *MockPlaylistRepository) AddScenes(playlistID uint, sceneIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddScenes", playlistID, sceneIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddScenes indicates an expected call of AddScenes.
func (mr *MockPlaylistRepositoryMockRecorder) AddScenes(playlistID, sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddScenes", reflect.TypeOf((*MockPlaylistRepository)(nil).AddScenes), playlistID, sceneIDs)
}

// Create mocks base method.
func (m *MockPlaylistRepository) Create(playlist *data.Playlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", playlist)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPlaylistRepositoryMockRecorder) Create(playlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlaylistRepository)(nil).Create), playlist)
}

// Delete mocks base method.
func (m *MockPlaylistRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlaylistRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlaylistRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockPlaylistRepository) GetByID(id uint) (*data.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlaylistRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlaylistRepository)(nil).GetByID), id)
}

// GetByUUID mocks base method.
func (m *MockPlaylistRepository) GetByUUID(uuid string) (*data.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", uuid)
	ret0, _ := ret[0].(*data.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockPlaylistRepositoryMockRecorder) GetByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockPlaylistRepository)(nil).GetByUUID), uuid)
}

// GetLikeCount mocks base method.
func (m *MockPlaylistRepository) GetLikeCount(playlistID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeCount", playlistID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikeCount indicates an expected call of GetLikeCount.
func (mr *MockPlaylistRepositoryMockRecorder) GetLikeCount(playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeCount", reflect.TypeOf((*MockPlaylistRepository)(nil).GetLikeCount), playlistID)
}

// GetLikeStatus mocks base method.
func (m *MockPlaylistRepository) GetLikeStatus(userID, playlistID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeStatus", userID, playlistID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikeStatus indicates an expected call of GetLikeStatus.
func (mr *MockPlaylistRepositoryMockRecorder) GetLikeStatus(userID, playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeStatus", reflect.TypeOf((*MockPlaylistRepository)(nil).GetLikeStatus), userID, playlistID)
}

// GetMaxPosition mocks base method.
func (m *MockPlaylistRepository) GetMaxPosition(playlistID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPosition", playlistID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxPosition indicates an expected call of GetMaxPosition.
func (mr *MockPlaylistRepositoryMockRecorder) GetMaxPosition(playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPosition", reflect.TypeOf((*MockPlaylistRepository)(nil).GetMaxPosition), playlistID)
}

// GetPlaylistScenes mocks base method.
func (m *MockPlaylistRepository) GetPlaylistScenes(playlistID uint) ([]data.PlaylistScene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistScenes", playlistID)
	ret0, _ := ret[0].([]data.PlaylistScene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistScenes indicates an expected call of GetPlaylistScenes.
func (mr *MockPlaylistRepositoryMockRecorder) GetPlaylistScenes(playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistScenes", reflect.TypeOf((*MockPlaylistRepository)(nil).GetPlaylistScenes), playlistID)
}

// GetPlaylistTags mocks base method.
func (m *MockPlaylistRepository) GetPlaylistTags(playlistID uint) ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistTags", playlistID)
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistTags indicates an expected call of GetPlaylistTags.
func (mr *MockPlaylistRepositoryMockRecorder) GetPlaylistTags(playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistTags", reflect.TypeOf((*MockPlaylistRepository)(nil).GetPlaylistTags), playlistID)
}

// GetProgress mocks base method.
func (m *MockPlaylistRepository) GetProgress(userID, playlistID uint) (*data.PlaylistProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress", userID, playlistID)
	ret0, _ := ret[0].(*data.PlaylistProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockPlaylistRepositoryMockRecorder) GetProgress(userID, playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockPlaylistRepository)(nil).GetProgress), userID, playlistID)
}

// GetSceneCount mocks base method.
func (m *MockPlaylistRepository) GetSceneCount(playlistID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneCount", playlistID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneCount indicates an expected call of GetSceneCount.
func (mr *MockPlaylistRepositoryMockRecorder) GetSceneCount(playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneCount", reflect.TypeOf((*MockPlaylistRepository)(nil).GetSceneCount), playlistID)
}

// GetThumbnailScenes mocks base method.
func (m *MockPlaylistRepository) GetThumbnailScenes(playlistID uint, limit int) ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnailScenes", playlistID, limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnailScenes indicates an expected call of GetThumbnailScenes.
func (mr *MockPlaylistRepositoryMockRecorder) GetThumbnailScenes(playlistID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnailScenes", reflect.TypeOf((*MockPlaylistRepository)(nil).GetThumbnailScenes), playlistID, limit)
}

// GetTotalDuration mocks base method.
func (m *MockPlaylistRepository) GetTotalDuration(playlistID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalDuration", playlistID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalDuration indicates an expected call of GetTotalDuration.
func (mr *MockPlaylistRepositoryMockRecorder) GetTotalDuration(playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalDuration", reflect.TypeOf((*MockPlaylistRepository)(nil).GetTotalDuration), playlistID)
}

// List mocks base method.
func (m *MockPlaylistRepository) List(params data.PlaylistListParams) ([]data.Playlist, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", params)
	ret0, _ := ret[0].([]data.Playlist)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPlaylistRepositoryMockRecorder) List(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPlaylistRepository)(nil).List), params)
}

// RemoveScene mocks base method.
func (m *MockPlaylistRepository) RemoveScene(playlistID, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveScene", playlistID, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveScene indicates an expected call of RemoveScene.
func (mr *MockPlaylistRepositoryMockRecorder) RemoveScene(playlistID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveScene", reflect.TypeOf((*MockPlaylistRepository)(nil).RemoveScene), playlistID, sceneID)
}

// RemoveScenes mocks base method.
func (m *MockPlaylistRepository) RemoveScenes(playlistID uint, sceneIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveScenes", playlistID, sceneIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveScenes indicates an expected call of RemoveScenes.
func (mr *MockPlaylistRepositoryMockRecorder) RemoveScenes(playlistID, sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveScenes", reflect.TypeOf((*MockPlaylistRepository)(nil).RemoveScenes), playlistID, sceneIDs)
}

// ReorderScenes mocks base method.
func (m *MockPlaylistRepository) ReorderScenes(playlistID uint, sceneIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderScenes", playlistID, sceneIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderScenes indicates an expected call of ReorderScenes.
func (mr *MockPlaylistRepositoryMockRecorder) ReorderScenes(playlistID, sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderScenes", reflect.TypeOf((*MockPlaylistRepository)(nil).ReorderScenes), playlistID, sceneIDs)
}

// SetPlaylistTags mocks base method.
func (m *MockPlaylistRepository) SetPlaylistTags(playlistID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPlaylistTags", playlistID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPlaylistTags indicates an expected call of SetPlaylistTags.
func (mr *MockPlaylistRepositoryMockRecorder) SetPlaylistTags(playlistID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlaylistTags", reflect.TypeOf((*MockPlaylistRepository)(nil).SetPlaylistTags), playlistID, tagIDs)
}

// ToggleLike mocks base method.
func (m *MockPlaylistRepository) ToggleLike(userID, playlistID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", userID, playlistID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleLike indicates an expected call of ToggleLike.
func (mr *MockPlaylistRepositoryMockRecorder) ToggleLike(userID, playlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockPlaylistRepository)(nil).ToggleLike), userID, playlistID)
}

// Update mocks base method.
func (m *MockPlaylistRepository) Update(playlist *data.Playlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", playlist)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlaylistRepositoryMockRecorder) Update(playlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlaylistRepository)(nil).Update), playlist)
}

// UpsertProgress mocks base method.
func (m *MockPlaylistRepository) UpsertProgress(userID, playlistID, sceneID uint, positionS float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProgress", userID, playlistID, sceneID, positionS)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProgress indicates an expected call of UpsertProgress.
func (mr *MockPlaylistRepositoryMockRecorder) UpsertProgress(userID, playlistID, sceneID, positionS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProgress", reflect.TypeOf((*MockPlaylistRepository)(nil).UpsertProgress), userID, playlistID, sceneID, positionS)
}
