// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: PoolConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_pool_config_repository.go -package=mocks goonhub/internal/data PoolConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPoolConfigRepository is a mock of PoolConfigRepository interface.
type MockPoolConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPoolConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockPoolConfigRepositoryMockRecorder is the mock recorder for MockPoolConfigRepository.
type MockPoolConfigRepositoryMockRecorder struct {
	mock *MockPoolConfigRepository
}

// NewMockPoolConfigRepository creates a new mock instance.
func NewMockPoolConfigRepository(ctrl *gomock.Controller) *MockPoolConfigRepository {
	mock := &MockPoolConfigRepository{ctrl: ctrl}
	mock.recorder = &MockPoolConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolConfigRepository) EXPECT() *MockPoolConfigRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPoolConfigRepository) Get() (*data.PoolConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*data.PoolConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPoolConfigRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPoolConfigRepository)(nil).Get))
}

// Upsert mocks base method.
func (m *MockPoolConfigRepository) Upsert(record *data.PoolConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPoolConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPoolConfigRepository)(nil).Upsert), record)
}
