// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: SavedSearchRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_saved_search_repository.go -package=mocks goonhub/internal/data SavedSearchRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSavedSearchRepository is a mock of SavedSearchRepository interface.
type MockSavedSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSavedSearchRepositoryMockRecorder
	isgomock struct{}
}

// MockSavedSearchRepositoryMockRecorder is the mock recorder for MockSavedSearchRepository.
type MockSavedSearchRepositoryMockRecorder struct {
	mock *MockSavedSearchRepository
}

// NewMockSavedSearchRepository creates a new mock instance.
func NewMockSavedSearchRepository(ctrl *gomock.Controller) *MockSavedSearchRepository {
	mock := &MockSavedSearchRepository{ctrl: ctrl}
	mock.recorder = &MockSavedSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSavedSearchRepository) EXPECT() *MockSavedSearchRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSavedSearchRepository) Create(search *data.SavedSearch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", search)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSavedSearchRepositoryMockRecorder) Create(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSavedSearchRepository)(nil).Create), search)
}

// Delete mocks base method.
func (m *MockSavedSearchRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSavedSearchRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSavedSearchRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockSavedSearchRepository) GetByID(id uint) (*data.SavedSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.SavedSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSavedSearchRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSavedSearchRepository)(nil).GetByID), id)
}

// GetByUUID mocks base method.
func (m *MockSavedSearchRepository) GetByUUID(uuid string) (*data.SavedSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", uuid)
	ret0, _ := ret[0].(*data.SavedSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockSavedSearchRepositoryMockRecorder) GetByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockSavedSearchRepository)(nil).GetByUUID), uuid)
}

// ListByUserID mocks base method.
func (m *MockSavedSearchRepository) ListByUserID(userID uint) ([]data.SavedSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", userID)
	ret0, _ := ret[0].([]data.SavedSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockSavedSearchRepositoryMockRecorder) ListByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockSavedSearchRepository)(nil).ListByUserID), userID)
}

// Update mocks base method.
func (m *MockSavedSearchRepository) Update(search *data.SavedSearch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", search)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSavedSearchRepositoryMockRecorder) Update(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSavedSearchRepository)(nil).Update), search)
}
