// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: TagRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_tag_repository.go -package=mocks goonhub/internal/data TagRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// BulkAddTagsToScenes mocks base method.
func (m *MockTagRepository) BulkAddTagsToScenes(sceneIDs, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAddTagsToScenes", sceneIDs, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkAddTagsToScenes indicates an expected call of BulkAddTagsToScenes.
func (mr *MockTagRepositoryMockRecorder) BulkAddTagsToScenes(sceneIDs, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAddTagsToScenes", reflect.TypeOf((*MockTagRepository)(nil).BulkAddTagsToScenes), sceneIDs, tagIDs)
}

// BulkRemoveTagsFromScenes mocks base method.
func (m *MockTagRepository) BulkRemoveTagsFromScenes(sceneIDs, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkRemoveTagsFromScenes", sceneIDs, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkRemoveTagsFromScenes indicates an expected call of BulkRemoveTagsFromScenes.
func (mr *MockTagRepositoryMockRecorder) BulkRemoveTagsFromScenes(sceneIDs, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkRemoveTagsFromScenes", reflect.TypeOf((*MockTagRepository)(nil).BulkRemoveTagsFromScenes), sceneIDs, tagIDs)
}

// BulkReplaceTagsForScenes mocks base method.
func (m *MockTagRepository) BulkReplaceTagsForScenes(sceneIDs, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkReplaceTagsForScenes", sceneIDs, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkReplaceTagsForScenes indicates an expected call of BulkReplaceTagsForScenes.
func (mr *MockTagRepositoryMockRecorder) BulkReplaceTagsForScenes(sceneIDs, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkReplaceTagsForScenes", reflect.TypeOf((*MockTagRepository)(nil).BulkReplaceTagsForScenes), sceneIDs, tagIDs)
}

// Create mocks base method.
func (m *MockTagRepository) Create(tag *data.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), tag)
}

// Delete mocks base method.
func (m *MockTagRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockTagRepository) GetByID(id uint) (*data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTagRepository)(nil).GetByID), id)
}

// GetByIDs mocks base method.
func (m *MockTagRepository) GetByIDs(ids []uint) ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ids)
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockTagRepositoryMockRecorder) GetByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockTagRepository)(nil).GetByIDs), ids)
}

// GetByNames mocks base method.
func (m *MockTagRepository) GetByNames(names []string) ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNames", names)
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNames indicates an expected call of GetByNames.
func (mr *MockTagRepositoryMockRecorder) GetByNames(names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNames", reflect.TypeOf((*MockTagRepository)(nil).GetByNames), names)
}

// GetIDsByNames mocks base method.
func (m *MockTagRepository) GetIDsByNames(names []string) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByNames", names)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByNames indicates an expected call of GetIDsByNames.
func (mr *MockTagRepositoryMockRecorder) GetIDsByNames(names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByNames", reflect.TypeOf((*MockTagRepository)(nil).GetIDsByNames), names)
}

// GetSceneIDsByTag mocks base method.
func (m *MockTagRepository) GetSceneIDsByTag(tagID uint, limit int) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneIDsByTag", tagID, limit)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneIDsByTag indicates an expected call of GetSceneIDsByTag.
func (mr *MockTagRepositoryMockRecorder) GetSceneIDsByTag(tagID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneIDsByTag", reflect.TypeOf((*MockTagRepository)(nil).GetSceneIDsByTag), tagID, limit)
}

// GetSceneTags mocks base method.
func (m *MockTagRepository) GetSceneTags(sceneID uint) ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneTags", sceneID)
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneTags indicates an expected call of GetSceneTags.
func (mr *MockTagRepositoryMockRecorder) GetSceneTags(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneTags", reflect.TypeOf((*MockTagRepository)(nil).GetSceneTags), sceneID)
}

// GetSceneTagsMultiple mocks base method.
func (m *MockTagRepository) GetSceneTagsMultiple(sceneIDs []uint) (map[uint][]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneTagsMultiple", sceneIDs)
	ret0, _ := ret[0].(map[uint][]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneTagsMultiple indicates an expected call of GetSceneTagsMultiple.
func (mr *MockTagRepositoryMockRecorder) GetSceneTagsMultiple(sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneTagsMultiple", reflect.TypeOf((*MockTagRepository)(nil).GetSceneTagsMultiple), sceneIDs)
}

// List mocks base method.
func (m *MockTagRepository) List() ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagRepository)(nil).List))
}

// ListWithCounts mocks base method.
func (m *MockTagRepository) ListWithCounts() ([]data.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithCounts")
	ret0, _ := ret[0].([]data.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithCounts indicates an expected call of ListWithCounts.
func (mr *MockTagRepositoryMockRecorder) ListWithCounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithCounts", reflect.TypeOf((*MockTagRepository)(nil).ListWithCounts))
}

// SetSceneTags mocks base method.
func (m *MockTagRepository) SetSceneTags(sceneID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSceneTags", sceneID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSceneTags indicates an expected call of SetSceneTags.
func (mr *MockTagRepositoryMockRecorder) SetSceneTags(sceneID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSceneTags", reflect.TypeOf((*MockTagRepository)(nil).SetSceneTags), sceneID, tagIDs)
}
