// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: MarkerRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_marker_repository.go -package=mocks goonhub/internal/data MarkerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMarkerRepository is a mock of MarkerRepository interface.
type MockMarkerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMarkerRepositoryMockRecorder
	isgomock struct{}
}

// MockMarkerRepositoryMockRecorder is the mock recorder for MockMarkerRepository.
type MockMarkerRepositoryMockRecorder struct {
	mock *MockMarkerRepository
}

// NewMockMarkerRepository creates a new mock instance.
func NewMockMarkerRepository(ctrl *gomock.Controller) *MockMarkerRepository {
	mock := &MockMarkerRepository{ctrl: ctrl}
	mock.recorder = &MockMarkerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarkerRepository) EXPECT() *MockMarkerRepositoryMockRecorder {
	return m.recorder
}

// AddMarkerTags mocks base method.
func (m *MockMarkerRepository) AddMarkerTags(markerID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMarkerTags", markerID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMarkerTags indicates an expected call of AddMarkerTags.
func (mr *MockMarkerRepositoryMockRecorder) AddMarkerTags(markerID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMarkerTags", reflect.TypeOf((*MockMarkerRepository)(nil).AddMarkerTags), markerID, tagIDs)
}

// ApplyLabelTagsToMarker mocks base method.
func (m *MockMarkerRepository) ApplyLabelTagsToMarker(userID, markerID uint, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyLabelTagsToMarker", userID, markerID, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyLabelTagsToMarker indicates an expected call of ApplyLabelTagsToMarker.
func (mr *MockMarkerRepositoryMockRecorder) ApplyLabelTagsToMarker(userID, markerID, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyLabelTagsToMarker", reflect.TypeOf((*MockMarkerRepository)(nil).ApplyLabelTagsToMarker), userID, markerID, label)
}

// CountByUserAndScene mocks base method.
func (m *MockMarkerRepository) CountByUserAndScene(userID, sceneID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserAndScene", userID, sceneID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserAndScene indicates an expected call of CountByUserAndScene.
func (mr *MockMarkerRepositoryMockRecorder) CountByUserAndScene(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserAndScene", reflect.TypeOf((*MockMarkerRepository)(nil).CountByUserAndScene), userID, sceneID)
}

// Create mocks base method.
func (m *MockMarkerRepository) Create(marker *data.UserSceneMarker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", marker)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMarkerRepositoryMockRecorder) Create(marker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMarkerRepository)(nil).Create), marker)
}

// Delete mocks base method.
func (m *MockMarkerRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMarkerRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMarkerRepository)(nil).Delete), id)
}

// GetAllLabelTagsForUser mocks base method.
func (m *MockMarkerRepository) GetAllLabelTagsForUser(userID uint) (map[string][]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLabelTagsForUser", userID)
	ret0, _ := ret[0].(map[string][]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLabelTagsForUser indicates an expected call of GetAllLabelTagsForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetAllLabelTagsForUser(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLabelTagsForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetAllLabelTagsForUser), userID)
}

// GetAllMarkersForUser mocks base method.
func (m *MockMarkerRepository) GetAllMarkersForUser(userID uint, offset, limit int, sortBy string) ([]data.MarkerWithScene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMarkersForUser", userID, offset, limit, sortBy)
	ret0, _ := ret[0].([]data.MarkerWithScene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllMarkersForUser indicates an expected call of GetAllMarkersForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetAllMarkersForUser(userID, offset, limit, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMarkersForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetAllMarkersForUser), userID, offset, limit, sortBy)
}

// GetByID mocks base method.
func (m *MockMarkerRepository) GetByID(id uint) (*data.UserSceneMarker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.UserSceneMarker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMarkerRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMarkerRepository)(nil).GetByID), id)
}

// GetBySceneWithoutThumbnail mocks base method.
func (m *MockMarkerRepository) GetBySceneWithoutThumbnail(sceneID uint) ([]data.UserSceneMarker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySceneWithoutThumbnail", sceneID)
	ret0, _ := ret[0].([]data.UserSceneMarker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySceneWithoutThumbnail indicates an expected call of GetBySceneWithoutThumbnail.
func (mr *MockMarkerRepositoryMockRecorder) GetBySceneWithoutThumbnail(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySceneWithoutThumbnail", reflect.TypeOf((*MockMarkerRepository)(nil).GetBySceneWithoutThumbnail), sceneID)
}

// GetByUserAndScene mocks base method.
func (m *MockMarkerRepository) GetByUserAndScene(userID, sceneID uint) ([]data.UserSceneMarker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndScene", userID, sceneID)
	ret0, _ := ret[0].([]data.UserSceneMarker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndScene indicates an expected call of GetByUserAndScene.
func (mr *MockMarkerRepositoryMockRecorder) GetByUserAndScene(userID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndScene", reflect.TypeOf((*MockMarkerRepository)(nil).GetByUserAndScene), userID, sceneID)
}

// GetLabelGroupsForUser mocks base method.
func (m *MockMarkerRepository) GetLabelGroupsForUser(userID uint, offset, limit int, sortBy string) ([]data.MarkerLabelGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelGroupsForUser", userID, offset, limit, sortBy)
	ret0, _ := ret[0].([]data.MarkerLabelGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLabelGroupsForUser indicates an expected call of GetLabelGroupsForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetLabelGroupsForUser(userID, offset, limit, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelGroupsForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetLabelGroupsForUser), userID, offset, limit, sortBy)
}

// GetLabelSuggestionsForUser mocks base method.
func (m *MockMarkerRepository) GetLabelSuggestionsForUser(userID uint, limit int) ([]data.MarkerLabelSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelSuggestionsForUser", userID, limit)
	ret0, _ := ret[0].([]data.MarkerLabelSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelSuggestionsForUser indicates an expected call of GetLabelSuggestionsForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetLabelSuggestionsForUser(userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelSuggestionsForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetLabelSuggestionsForUser), userID, limit)
}

// GetLabelTags mocks base method.
func (m *MockMarkerRepository) GetLabelTags(userID uint, label string) ([]data.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelTags", userID, label)
	ret0, _ := ret[0].([]data.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelTags indicates an expected call of GetLabelTags.
func (mr *MockMarkerRepositoryMockRecorder) GetLabelTags(userID, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelTags", reflect.TypeOf((*MockMarkerRepository)(nil).GetLabelTags), userID, label)
}

// GetMarkerIDsByLabel mocks base method.
func (m *MockMarkerRepository) GetMarkerIDsByLabel(userID uint, label string) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarkerIDsByLabel", userID, label)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarkerIDsByLabel indicates an expected call of GetMarkerIDsByLabel.
func (mr *MockMarkerRepositoryMockRecorder) GetMarkerIDsByLabel(userID, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarkerIDsByLabel", reflect.TypeOf((*MockMarkerRepository)(nil).GetMarkerIDsByLabel), userID, label)
}

// GetMarkerTags mocks base method.
func (m *MockMarkerRepository) GetMarkerTags(markerID uint) ([]data.MarkerTagInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarkerTags", markerID)
	ret0, _ := ret[0].([]data.MarkerTagInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarkerTags indicates an expected call of GetMarkerTags.
func (mr *MockMarkerRepositoryMockRecorder) GetMarkerTags(markerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarkerTags", reflect.TypeOf((*MockMarkerRepository)(nil).GetMarkerTags), markerID)
}

// GetMarkerTagsMultiple mocks base method.
func (m *MockMarkerRepository) GetMarkerTagsMultiple(markerIDs []uint) (map[uint][]data.MarkerTagInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarkerTagsMultiple", markerIDs)
	ret0, _ := ret[0].(map[uint][]data.MarkerTagInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarkerTagsMultiple indicates an expected call of GetMarkerTagsMultiple.
func (mr *MockMarkerRepositoryMockRecorder) GetMarkerTagsMultiple(markerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarkerTagsMultiple", reflect.TypeOf((*MockMarkerRepository)(nil).GetMarkerTagsMultiple), markerIDs)
}

// GetMarkersByLabelForUser mocks base method.
func (m *MockMarkerRepository) GetMarkersByLabelForUser(userID uint, label string, offset, limit int) ([]data.MarkerWithScene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarkersByLabelForUser", userID, label, offset, limit)
	ret0, _ := ret[0].([]data.MarkerWithScene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMarkersByLabelForUser indicates an expected call of GetMarkersByLabelForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetMarkersByLabelForUser(userID, label, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarkersByLabelForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetMarkersByLabelForUser), userID, label, offset, limit)
}

// GetRandomThumbnailsForLabels mocks base method.
func (m *MockMarkerRepository) GetRandomThumbnailsForLabels(userID uint, labels []string, perLabel int) (map[string][]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomThumbnailsForLabels", userID, labels, perLabel)
	ret0, _ := ret[0].(map[string][]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomThumbnailsForLabels indicates an expected call of GetRandomThumbnailsForLabels.
func (mr *MockMarkerRepositoryMockRecorder) GetRandomThumbnailsForLabels(userID, labels, perLabel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomThumbnailsForLabels", reflect.TypeOf((*MockMarkerRepository)(nil).GetRandomThumbnailsForLabels), userID, labels, perLabel)
}

// GetSceneIDsByLabels mocks base method.
func (m *MockMarkerRepository) GetSceneIDsByLabels(userID uint, labels []string) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneIDsByLabels", userID, labels)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneIDsByLabels indicates an expected call of GetSceneIDsByLabels.
func (mr *MockMarkerRepositoryMockRecorder) GetSceneIDsByLabels(userID, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneIDsByLabels", reflect.TypeOf((*MockMarkerRepository)(nil).GetSceneIDsByLabels), userID, labels)
}

// SetLabelTags mocks base method.
func (m *MockMarkerRepository) SetLabelTags(userID uint, label string, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabelTags", userID, label, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLabelTags indicates an expected call of SetLabelTags.
func (mr *MockMarkerRepositoryMockRecorder) SetLabelTags(userID, label, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabelTags", reflect.TypeOf((*MockMarkerRepository)(nil).SetLabelTags), userID, label, tagIDs)
}

// SetMarkerTags mocks base method.
func (m *MockMarkerRepository) SetMarkerTags(markerID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMarkerTags", markerID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMarkerTags indicates an expected call of SetMarkerTags.
func (mr *MockMarkerRepositoryMockRecorder) SetMarkerTags(markerID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMarkerTags", reflect.TypeOf((*MockMarkerRepository)(nil).SetMarkerTags), markerID, tagIDs)
}

// SyncMarkerTagsFromLabel mocks base method.
func (m *MockMarkerRepository) SyncMarkerTagsFromLabel(userID uint, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMarkerTagsFromLabel", userID, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMarkerTagsFromLabel indicates an expected call of SyncMarkerTagsFromLabel.
func (mr *MockMarkerRepositoryMockRecorder) SyncMarkerTagsFromLabel(userID, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMarkerTagsFromLabel", reflect.TypeOf((*MockMarkerRepository)(nil).SyncMarkerTagsFromLabel), userID, label)
}

// Update mocks base method.
func (m *MockMarkerRepository) Update(marker *data.UserSceneMarker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", marker)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMarkerRepositoryMockRecorder) Update(marker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMarkerRepository)(nil).Update), marker)
}
