// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ActorRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_actor_repository.go -package=mocks goonhub/internal/data ActorRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActorRepository is a mock of ActorRepository interface.
type MockActorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepositoryMockRecorder
	isgomock struct{}
}

// MockActorRepositoryMockRecorder is the mock recorder for MockActorRepository.
type MockActorRepositoryMockRecorder struct {
	mock *MockActorRepository
}

// NewMockActorRepository creates a new mock instance.
func NewMockActorRepository(ctrl *gomock.Controller) *MockActorRepository {
	mock := &MockActorRepository{ctrl: ctrl}
	mock.recorder = &MockActorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepository) EXPECT() *MockActorRepositoryMockRecorder {
	return m.recorder
}

// BulkAddActorsToScenes mocks base method.
func (m *MockActorRepository) BulkAddActorsToScenes(sceneIDs, actorIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAddActorsToScenes", sceneIDs, actorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkAddActorsToScenes indicates an expected call of BulkAddActorsToScenes.
func (mr *MockActorRepositoryMockRecorder) BulkAddActorsToScenes(sceneIDs, actorIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAddActorsToScenes", reflect.TypeOf((*MockActorRepository)(nil).BulkAddActorsToScenes), sceneIDs, actorIDs)
}

// BulkRemoveActorsFromScenes mocks base method.
func (m *MockActorRepository) BulkRemoveActorsFromScenes(sceneIDs, actorIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkRemoveActorsFromScenes", sceneIDs, actorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkRemoveActorsFromScenes indicates an expected call of BulkRemoveActorsFromScenes.
func (mr *MockActorRepositoryMockRecorder) BulkRemoveActorsFromScenes(sceneIDs, actorIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkRemoveActorsFromScenes", reflect.TypeOf((*MockActorRepository)(nil).BulkRemoveActorsFromScenes), sceneIDs, actorIDs)
}

// BulkReplaceActorsForScenes mocks base method.
func (m *MockActorRepository) BulkReplaceActorsForScenes(sceneIDs, actorIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkReplaceActorsForScenes", sceneIDs, actorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkReplaceActorsForScenes indicates an expected call of BulkReplaceActorsForScenes.
func (mr *MockActorRepositoryMockRecorder) BulkReplaceActorsForScenes(sceneIDs, actorIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkReplaceActorsForScenes", reflect.TypeOf((*MockActorRepository)(nil).BulkReplaceActorsForScenes), sceneIDs, actorIDs)
}

// Create mocks base method.
func (m *MockActorRepository) Create(actor *data.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActorRepositoryMockRecorder) Create(actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActorRepository)(nil).Create), actor)
}

// Delete mocks base method.
func (m *MockActorRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActorRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActorRepository)(nil).Delete), id)
}

// GetActorSceneIDs mocks base method.
func (m *MockActorRepository) GetActorSceneIDs(actorID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorSceneIDs", actorID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorSceneIDs indicates an expected call of GetActorSceneIDs.
func (mr *MockActorRepositoryMockRecorder) GetActorSceneIDs(actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorSceneIDs", reflect.TypeOf((*MockActorRepository)(nil).GetActorSceneIDs), actorID)
}

// GetActorScenes mocks base method.
func (m *MockActorRepository) GetActorScenes(actorID uint, page, limit int) ([]data.Scene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorScenes", actorID, page, limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActorScenes indicates an expected call of GetActorScenes.
func (mr *MockActorRepositoryMockRecorder) GetActorScenes(actorID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorScenes", reflect.TypeOf((*MockActorRepository)(nil).GetActorScenes), actorID, page, limit)
}

// GetByID mocks base method.
func (m *MockActorRepository) GetByID(id uint) (*data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActorRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActorRepository)(nil).GetByID), id)
}

// GetByIDs mocks base method.
func (m *MockActorRepository) GetByIDs(ids []uint) ([]data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ids)
	ret0, _ := ret[0].([]data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockActorRepositoryMockRecorder) GetByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockActorRepository)(nil).GetByIDs), ids)
}

// GetByUUID mocks base method.
func (m *MockActorRepository) GetByUUID(uuid string) (*data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", uuid)
	ret0, _ := ret[0].(*data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockActorRepositoryMockRecorder) GetByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockActorRepository)(nil).GetByUUID), uuid)
}

// GetSceneActors mocks base method.
func (m *MockActorRepository) GetSceneActors(sceneID uint) ([]data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneActors", sceneID)
	ret0, _ := ret[0].([]data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneActors indicates an expected call of GetSceneActors.
func (mr *MockActorRepositoryMockRecorder) GetSceneActors(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneActors", reflect.TypeOf((*MockActorRepository)(nil).GetSceneActors), sceneID)
}

// GetSceneActorsMultiple mocks base method.
func (m *MockActorRepository) GetSceneActorsMultiple(sceneIDs []uint) (map[uint][]data.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneActorsMultiple", sceneIDs)
	ret0, _ := ret[0].(map[uint][]data.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneActorsMultiple indicates an expected call of GetSceneActorsMultiple.
func (mr *MockActorRepositoryMockRecorder) GetSceneActorsMultiple(sceneIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneActorsMultiple", reflect.TypeOf((*MockActorRepository)(nil).GetSceneActorsMultiple), sceneIDs)
}

// GetSceneCount mocks base method.
func (m *MockActorRepository) GetSceneCount(actorID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneCount", actorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneCount indicates an expected call of GetSceneCount.
func (mr *MockActorRepositoryMockRecorder) GetSceneCount(actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneCount", reflect.TypeOf((*MockActorRepository)(nil).GetSceneCount), actorID)
}

// List mocks base method.
func (m *MockActorRepository) List(page, limit int, sort string, genders []string) ([]data.ActorWithCount, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit, sort, genders)
	ret0, _ := ret[0].([]data.ActorWithCount)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockActorRepositoryMockRecorder) List(page, limit, sort, genders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActorRepository)(nil).List), page, limit, sort, genders)
}

// Search mocks base method.
func (m *MockActorRepository) Search(query string, page, limit int, sort string, genders []string) ([]data.ActorWithCount, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query, page, limit, sort, genders)
	ret0, _ := ret[0].([]data.ActorWithCount)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockActorRepositoryMockRecorder) Search(query, page, limit, sort, genders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockActorRepository)(nil).Search), query, page, limit, sort, genders)
}

// SetSceneActors mocks base method.
func (m *MockActorRepository) SetSceneActors(sceneID uint, actorIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSceneActors", sceneID, actorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSceneActors indicates an expected call of SetSceneActors.
func (mr *MockActorRepositoryMockRecorder) SetSceneActors(sceneID, actorIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSceneActors", reflect.TypeOf((*MockActorRepository)(nil).SetSceneActors), sceneID, actorIDs)
}

// Update mocks base method.
func (m *MockActorRepository) Update(actor *data.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockActorRepositoryMockRecorder) Update(actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActorRepository)(nil).Update), actor)
}
