// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: RevokedTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_revoked_token_repository.go -package=mocks goonhub/internal/data RevokedTokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRevokedTokenRepository is a mock of RevokedTokenRepository interface.
type MockRevokedTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRevokedTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRevokedTokenRepositoryMockRecorder is the mock recorder for MockRevokedTokenRepository.
type MockRevokedTokenRepositoryMockRecorder struct {
	mock *MockRevokedTokenRepository
}

// NewMockRevokedTokenRepository creates a new mock instance.
func NewMockRevokedTokenRepository(ctrl *gomock.Controller) *MockRevokedTokenRepository {
	mock := &MockRevokedTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRevokedTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevokedTokenRepository) EXPECT() *MockRevokedTokenRepositoryMockRecorder {
	return m.recorder
}

// CleanupExpired mocks base method.
func (m *MockRevokedTokenRepository) CleanupExpired() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockRevokedTokenRepositoryMockRecorder) CleanupExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockRevokedTokenRepository)(nil).CleanupExpired))
}

// Create mocks base method.
func (m *MockRevokedTokenRepository) Create(token *data.RevokedToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRevokedTokenRepositoryMockRecorder) Create(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRevokedTokenRepository)(nil).Create), token)
}

// IsRevoked mocks base method.
func (m *MockRevokedTokenRepository) IsRevoked(tokenHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", tokenHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRevoked indicates an expected call of IsRevoked.
func (mr *MockRevokedTokenRepositoryMockRecorder) IsRevoked(tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockRevokedTokenRepository)(nil).IsRevoked), tokenHash)
}
