// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: InteractionRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_interaction_repository.go -package=mocks goonhub/internal/data InteractionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractionRepository is a mock of InteractionRepository interface.
type MockInteractionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionRepositoryMockRecorder
	isgomock struct{}
}

// MockInteractionRepositoryMockRecorder is the mock recorder for MockInteractionRepository.
type MockInteractionRepositoryMockRecorder struct {
	mock *MockInteractionRepository
}

// NewMockInteractionRepository creates a new mock instance.
func NewMockInteractionRepository(ctrl *gomock.Controller) *MockInteractionRepository {
	mock := &MockInteractionRepository{ctrl: ctrl}
	mock.recorder = &MockInteractionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractionRepository) EXPECT() *MockInteractionRepositoryMockRecorder {
	return m.recorder
}

// DeleteLike mocks base method.
func (m *MockInteractionRepository) DeleteLike(userID, videoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLike", userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLike indicates an expected call of DeleteLike.
func (mr *MockInteractionRepositoryMockRecorder) DeleteLike(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLike", reflect.TypeOf((*MockInteractionRepository)(nil).DeleteLike), userID, videoID)
}

// DeleteRating mocks base method.
func (m *MockInteractionRepository) DeleteRating(userID, videoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRating", userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRating indicates an expected call of DeleteRating.
func (mr *MockInteractionRepositoryMockRecorder) DeleteRating(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRating", reflect.TypeOf((*MockInteractionRepository)(nil).DeleteRating), userID, videoID)
}

// GetAllInteractions mocks base method.
func (m *MockInteractionRepository) GetAllInteractions(userID, videoID uint) (*data.VideoInteractions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInteractions", userID, videoID)
	ret0, _ := ret[0].(*data.VideoInteractions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInteractions indicates an expected call of GetAllInteractions.
func (mr *MockInteractionRepositoryMockRecorder) GetAllInteractions(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInteractions", reflect.TypeOf((*MockInteractionRepository)(nil).GetAllInteractions), userID, videoID)
}

// GetJizzedCount mocks base method.
func (m *MockInteractionRepository) GetJizzedCount(userID, videoID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJizzedCount", userID, videoID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJizzedCount indicates an expected call of GetJizzedCount.
func (mr *MockInteractionRepositoryMockRecorder) GetJizzedCount(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJizzedCount", reflect.TypeOf((*MockInteractionRepository)(nil).GetJizzedCount), userID, videoID)
}

// GetJizzedVideoIDs mocks base method.
func (m *MockInteractionRepository) GetJizzedVideoIDs(userID uint, minCount, maxCount int) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJizzedVideoIDs", userID, minCount, maxCount)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJizzedVideoIDs indicates an expected call of GetJizzedVideoIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetJizzedVideoIDs(userID, minCount, maxCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJizzedVideoIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetJizzedVideoIDs), userID, minCount, maxCount)
}

// GetLikedVideoIDs mocks base method.
func (m *MockInteractionRepository) GetLikedVideoIDs(userID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedVideoIDs", userID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikedVideoIDs indicates an expected call of GetLikedVideoIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetLikedVideoIDs(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedVideoIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetLikedVideoIDs), userID)
}

// GetRatedVideoIDs mocks base method.
func (m *MockInteractionRepository) GetRatedVideoIDs(userID uint, minRating, maxRating float64) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatedVideoIDs", userID, minRating, maxRating)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatedVideoIDs indicates an expected call of GetRatedVideoIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetRatedVideoIDs(userID, minRating, maxRating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatedVideoIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetRatedVideoIDs), userID, minRating, maxRating)
}

// GetRating mocks base method.
func (m *MockInteractionRepository) GetRating(userID, videoID uint) (*data.UserVideoRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", userID, videoID)
	ret0, _ := ret[0].(*data.UserVideoRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockInteractionRepositoryMockRecorder) GetRating(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockInteractionRepository)(nil).GetRating), userID, videoID)
}

// GetRatingsByVideoIDs mocks base method.
func (m *MockInteractionRepository) GetRatingsByVideoIDs(userID uint, videoIDs []uint) (map[uint]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatingsByVideoIDs", userID, videoIDs)
	ret0, _ := ret[0].(map[uint]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatingsByVideoIDs indicates an expected call of GetRatingsByVideoIDs.
func (mr *MockInteractionRepositoryMockRecorder) GetRatingsByVideoIDs(userID, videoIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatingsByVideoIDs", reflect.TypeOf((*MockInteractionRepository)(nil).GetRatingsByVideoIDs), userID, videoIDs)
}

// IncrementJizzed mocks base method.
func (m *MockInteractionRepository) IncrementJizzed(userID, videoID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementJizzed", userID, videoID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementJizzed indicates an expected call of IncrementJizzed.
func (mr *MockInteractionRepositoryMockRecorder) IncrementJizzed(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementJizzed", reflect.TypeOf((*MockInteractionRepository)(nil).IncrementJizzed), userID, videoID)
}

// IsLiked mocks base method.
func (m *MockInteractionRepository) IsLiked(userID, videoID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", userID, videoID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockInteractionRepositoryMockRecorder) IsLiked(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockInteractionRepository)(nil).IsLiked), userID, videoID)
}

// SetLike mocks base method.
func (m *MockInteractionRepository) SetLike(userID, videoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLike", userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLike indicates an expected call of SetLike.
func (mr *MockInteractionRepositoryMockRecorder) SetLike(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLike", reflect.TypeOf((*MockInteractionRepository)(nil).SetLike), userID, videoID)
}

// UpsertRating mocks base method.
func (m *MockInteractionRepository) UpsertRating(userID, videoID uint, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRating", userID, videoID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRating indicates an expected call of UpsertRating.
func (mr *MockInteractionRepositoryMockRecorder) UpsertRating(userID, videoID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRating", reflect.TypeOf((*MockInteractionRepository)(nil).UpsertRating), userID, videoID, rating)
}
