// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: VideoRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_video_repository.go -package=mocks goonhub/internal/data VideoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVideoRepository is a mock of VideoRepository interface.
type MockVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockVideoRepositoryMockRecorder is the mock recorder for MockVideoRepository.
type MockVideoRepositoryMockRecorder struct {
	mock *MockVideoRepository
}

// NewMockVideoRepository creates a new mock instance.
func NewMockVideoRepository(ctrl *gomock.Controller) *MockVideoRepository {
	mock := &MockVideoRepository{ctrl: ctrl}
	mock.recorder = &MockVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoRepository) EXPECT() *MockVideoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoRepository) Create(video *data.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVideoRepositoryMockRecorder) Create(video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoRepository)(nil).Create), video)
}

// Delete mocks base method.
func (m *MockVideoRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockVideoRepository) GetByID(id uint) (*data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVideoRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVideoRepository)(nil).GetByID), id)
}

// GetPendingProcessing mocks base method.
func (m *MockVideoRepository) GetPendingProcessing() ([]data.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingProcessing")
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingProcessing indicates an expected call of GetPendingProcessing.
func (mr *MockVideoRepositoryMockRecorder) GetPendingProcessing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingProcessing", reflect.TypeOf((*MockVideoRepository)(nil).GetPendingProcessing))
}

// List mocks base method.
func (m *MockVideoRepository) List(page, limit int) ([]data.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]data.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVideoRepositoryMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVideoRepository)(nil).List), page, limit)
}

// UpdateMetadata mocks base method.
func (m *MockVideoRepository) UpdateMetadata(id uint, duration, width, height int, thumbnailPath, spriteSheetPath, vttPath string, spriteSheetCount, thumbnailWidth, thumbnailHeight int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockVideoRepositoryMockRecorder) UpdateMetadata(id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockVideoRepository)(nil).UpdateMetadata), id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight)
}

// UpdateProcessingStatus mocks base method.
func (m *MockVideoRepository) UpdateProcessingStatus(id uint, status, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", id, status, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockVideoRepositoryMockRecorder) UpdateProcessingStatus(id, status, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockVideoRepository)(nil).UpdateProcessingStatus), id, status, errorMsg)
}
