// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: StoragePathRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_storage_path_repository.go -package=mocks goonhub/internal/data StoragePathRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStoragePathRepository is a mock of StoragePathRepository interface.
type MockStoragePathRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoragePathRepositoryMockRecorder
	isgomock struct{}
}

// MockStoragePathRepositoryMockRecorder is the mock recorder for MockStoragePathRepository.
type MockStoragePathRepositoryMockRecorder struct {
	mock *MockStoragePathRepository
}

// NewMockStoragePathRepository creates a new mock instance.
func NewMockStoragePathRepository(ctrl *gomock.Controller) *MockStoragePathRepository {
	mock := &MockStoragePathRepository{ctrl: ctrl}
	mock.recorder = &MockStoragePathRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoragePathRepository) EXPECT() *MockStoragePathRepositoryMockRecorder {
	return m.recorder
}

// ClearDefault mocks base method.
func (m *MockStoragePathRepository) ClearDefault() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefault")
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefault indicates an expected call of ClearDefault.
func (mr *MockStoragePathRepositoryMockRecorder) ClearDefault() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefault", reflect.TypeOf((*MockStoragePathRepository)(nil).ClearDefault))
}

// Count mocks base method.
func (m *MockStoragePathRepository) Count() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockStoragePathRepositoryMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockStoragePathRepository)(nil).Count))
}

// Create mocks base method.
func (m *MockStoragePathRepository) Create(storagePath *data.StoragePath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", storagePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoragePathRepositoryMockRecorder) Create(storagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStoragePathRepository)(nil).Create), storagePath)
}

// Delete mocks base method.
func (m *MockStoragePathRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoragePathRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStoragePathRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockStoragePathRepository) GetByID(id uint) (*data.StoragePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.StoragePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStoragePathRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStoragePathRepository)(nil).GetByID), id)
}

// GetByPath mocks base method.
func (m *MockStoragePathRepository) GetByPath(path string) (*data.StoragePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", path)
	ret0, _ := ret[0].(*data.StoragePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockStoragePathRepositoryMockRecorder) GetByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockStoragePathRepository)(nil).GetByPath), path)
}

// GetDefault mocks base method.
func (m *MockStoragePathRepository) GetDefault() (*data.StoragePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefault")
	ret0, _ := ret[0].(*data.StoragePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefault indicates an expected call of GetDefault.
func (mr *MockStoragePathRepositoryMockRecorder) GetDefault() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefault", reflect.TypeOf((*MockStoragePathRepository)(nil).GetDefault))
}

// List mocks base method.
func (m *MockStoragePathRepository) List() ([]data.StoragePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]data.StoragePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoragePathRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStoragePathRepository)(nil).List))
}

// Update mocks base method.
func (m *MockStoragePathRepository) Update(storagePath *data.StoragePath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", storagePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoragePathRepositoryMockRecorder) Update(storagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStoragePathRepository)(nil).Update), storagePath)
}
