// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: DLQRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_dlq_repository.go -package=mocks goonhub/internal/data DLQRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDLQRepository is a mock of DLQRepository interface.
type MockDLQRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDLQRepositoryMockRecorder
	isgomock struct{}
}

// MockDLQRepositoryMockRecorder is the mock recorder for MockDLQRepository.
type MockDLQRepositoryMockRecorder struct {
	mock *MockDLQRepository
}

// NewMockDLQRepository creates a new mock instance.
func NewMockDLQRepository(ctrl *gomock.Controller) *MockDLQRepository {
	mock := &MockDLQRepository{ctrl: ctrl}
	mock.recorder = &MockDLQRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDLQRepository) EXPECT() *MockDLQRepositoryMockRecorder {
	return m.recorder
}

// AutoAbandon mocks base method.
func (m *MockDLQRepository) AutoAbandon(olderThan time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoAbandon", olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutoAbandon indicates an expected call of AutoAbandon.
func (mr *MockDLQRepositoryMockRecorder) AutoAbandon(olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoAbandon", reflect.TypeOf((*MockDLQRepository)(nil).AutoAbandon), olderThan)
}

// CountByStatus mocks base method.
func (m *MockDLQRepository) CountByStatus(status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockDLQRepositoryMockRecorder) CountByStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockDLQRepository)(nil).CountByStatus), status)
}

// Create mocks base method.
func (m *MockDLQRepository) Create(entry *data.DLQEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDLQRepositoryMockRecorder) Create(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDLQRepository)(nil).Create), entry)
}

// Delete mocks base method.
func (m *MockDLQRepository) Delete(jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDLQRepositoryMockRecorder) Delete(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDLQRepository)(nil).Delete), jobID)
}

// GetByJobID mocks base method.
func (m *MockDLQRepository) GetByJobID(jobID string) (*data.DLQEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByJobID", jobID)
	ret0, _ := ret[0].(*data.DLQEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByJobID indicates an expected call of GetByJobID.
func (mr *MockDLQRepositoryMockRecorder) GetByJobID(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByJobID", reflect.TypeOf((*MockDLQRepository)(nil).GetByJobID), jobID)
}

// ListByStatus mocks base method.
func (m *MockDLQRepository) ListByStatus(status string, page, limit int) ([]data.DLQEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", status, page, limit)
	ret0, _ := ret[0].([]data.DLQEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockDLQRepositoryMockRecorder) ListByStatus(status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockDLQRepository)(nil).ListByStatus), status, page, limit)
}

// ListPending mocks base method.
func (m *MockDLQRepository) ListPending(page, limit int) ([]data.DLQEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", page, limit)
	ret0, _ := ret[0].([]data.DLQEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPending indicates an expected call of ListPending.
func (mr *MockDLQRepositoryMockRecorder) ListPending(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockDLQRepository)(nil).ListPending), page, limit)
}

// MarkAbandoned mocks base method.
func (m *MockDLQRepository) MarkAbandoned(jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAbandoned", jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAbandoned indicates an expected call of MarkAbandoned.
func (mr *MockDLQRepositoryMockRecorder) MarkAbandoned(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAbandoned", reflect.TypeOf((*MockDLQRepository)(nil).MarkAbandoned), jobID)
}

// UpdateStatus mocks base method.
func (m *MockDLQRepository) UpdateStatus(jobID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", jobID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDLQRepositoryMockRecorder) UpdateStatus(jobID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDLQRepository)(nil).UpdateStatus), jobID, status)
}
