// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: MarkerRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_marker_repository.go -package=mocks goonhub/internal/data MarkerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMarkerRepository is a mock of MarkerRepository interface.
type MockMarkerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMarkerRepositoryMockRecorder
	isgomock struct{}
}

// MockMarkerRepositoryMockRecorder is the mock recorder for MockMarkerRepository.
type MockMarkerRepositoryMockRecorder struct {
	mock *MockMarkerRepository
}

// NewMockMarkerRepository creates a new mock instance.
func NewMockMarkerRepository(ctrl *gomock.Controller) *MockMarkerRepository {
	mock := &MockMarkerRepository{ctrl: ctrl}
	mock.recorder = &MockMarkerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarkerRepository) EXPECT() *MockMarkerRepositoryMockRecorder {
	return m.recorder
}

// CountByUserAndVideo mocks base method.
func (m *MockMarkerRepository) CountByUserAndVideo(userID, videoID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserAndVideo", userID, videoID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserAndVideo indicates an expected call of CountByUserAndVideo.
func (mr *MockMarkerRepositoryMockRecorder) CountByUserAndVideo(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserAndVideo", reflect.TypeOf((*MockMarkerRepository)(nil).CountByUserAndVideo), userID, videoID)
}

// Create mocks base method.
func (m *MockMarkerRepository) Create(marker *data.UserVideoMarker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", marker)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMarkerRepositoryMockRecorder) Create(marker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMarkerRepository)(nil).Create), marker)
}

// Delete mocks base method.
func (m *MockMarkerRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMarkerRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMarkerRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockMarkerRepository) GetByID(id uint) (*data.UserVideoMarker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.UserVideoMarker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMarkerRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMarkerRepository)(nil).GetByID), id)
}

// GetByUserAndVideo mocks base method.
func (m *MockMarkerRepository) GetByUserAndVideo(userID, videoID uint) ([]data.UserVideoMarker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndVideo", userID, videoID)
	ret0, _ := ret[0].([]data.UserVideoMarker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndVideo indicates an expected call of GetByUserAndVideo.
func (mr *MockMarkerRepositoryMockRecorder) GetByUserAndVideo(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndVideo", reflect.TypeOf((*MockMarkerRepository)(nil).GetByUserAndVideo), userID, videoID)
}

// GetLabelGroupsForUser mocks base method.
func (m *MockMarkerRepository) GetLabelGroupsForUser(userID uint, offset, limit int, sortBy string) ([]data.MarkerLabelGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelGroupsForUser", userID, offset, limit, sortBy)
	ret0, _ := ret[0].([]data.MarkerLabelGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLabelGroupsForUser indicates an expected call of GetLabelGroupsForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetLabelGroupsForUser(userID, offset, limit, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelGroupsForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetLabelGroupsForUser), userID, offset, limit, sortBy)
}

// GetLabelSuggestionsForUser mocks base method.
func (m *MockMarkerRepository) GetLabelSuggestionsForUser(userID uint, limit int) ([]data.MarkerLabelSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelSuggestionsForUser", userID, limit)
	ret0, _ := ret[0].([]data.MarkerLabelSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelSuggestionsForUser indicates an expected call of GetLabelSuggestionsForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetLabelSuggestionsForUser(userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelSuggestionsForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetLabelSuggestionsForUser), userID, limit)
}

// GetMarkersByLabelForUser mocks base method.
func (m *MockMarkerRepository) GetMarkersByLabelForUser(userID uint, label string, offset, limit int) ([]data.MarkerWithVideo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarkersByLabelForUser", userID, label, offset, limit)
	ret0, _ := ret[0].([]data.MarkerWithVideo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMarkersByLabelForUser indicates an expected call of GetMarkersByLabelForUser.
func (mr *MockMarkerRepositoryMockRecorder) GetMarkersByLabelForUser(userID, label, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarkersByLabelForUser", reflect.TypeOf((*MockMarkerRepository)(nil).GetMarkersByLabelForUser), userID, label, offset, limit)
}

// Update mocks base method.
func (m *MockMarkerRepository) Update(marker *data.UserVideoMarker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", marker)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMarkerRepositoryMockRecorder) Update(marker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMarkerRepository)(nil).Update), marker)
}
