// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: TriggerConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_trigger_config_repository.go -package=mocks goonhub/internal/data TriggerConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTriggerConfigRepository is a mock of TriggerConfigRepository interface.
type MockTriggerConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockTriggerConfigRepositoryMockRecorder is the mock recorder for MockTriggerConfigRepository.
type MockTriggerConfigRepositoryMockRecorder struct {
	mock *MockTriggerConfigRepository
}

// NewMockTriggerConfigRepository creates a new mock instance.
func NewMockTriggerConfigRepository(ctrl *gomock.Controller) *MockTriggerConfigRepository {
	mock := &MockTriggerConfigRepository{ctrl: ctrl}
	mock.recorder = &MockTriggerConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerConfigRepository) EXPECT() *MockTriggerConfigRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockTriggerConfigRepository) GetAll() ([]data.TriggerConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]data.TriggerConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTriggerConfigRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTriggerConfigRepository)(nil).GetAll))
}

// GetByPhase mocks base method.
func (m *MockTriggerConfigRepository) GetByPhase(phase string) (*data.TriggerConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhase", phase)
	ret0, _ := ret[0].(*data.TriggerConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhase indicates an expected call of GetByPhase.
func (mr *MockTriggerConfigRepositoryMockRecorder) GetByPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhase", reflect.TypeOf((*MockTriggerConfigRepository)(nil).GetByPhase), phase)
}

// Upsert mocks base method.
func (m *MockTriggerConfigRepository) Upsert(record *data.TriggerConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTriggerConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTriggerConfigRepository)(nil).Upsert), record)
}
