// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: DuplicateRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_duplicate_repository.go -package=mocks goonhub/internal/data DuplicateRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDuplicateRepository is a mock of DuplicateRepository interface.
type MockDuplicateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDuplicateRepositoryMockRecorder
	isgomock struct{}
}

// MockDuplicateRepositoryMockRecorder is the mock recorder for MockDuplicateRepository.
type MockDuplicateRepositoryMockRecorder struct {
	mock *MockDuplicateRepository
}

// NewMockDuplicateRepository creates a new mock instance.
func NewMockDuplicateRepository(ctrl *gomock.Controller) *MockDuplicateRepository {
	mock := &MockDuplicateRepository{ctrl: ctrl}
	mock.recorder = &MockDuplicateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuplicateRepository) EXPECT() *MockDuplicateRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockDuplicateRepository) AddMember(member *data.DuplicateGroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockDuplicateRepositoryMockRecorder) AddMember(member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockDuplicateRepository)(nil).AddMember), member)
}

// ClearMemberWinners mocks base method.
func (m *MockDuplicateRepository) ClearMemberWinners(groupID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearMemberWinners", groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearMemberWinners indicates an expected call of ClearMemberWinners.
func (mr *MockDuplicateRepositoryMockRecorder) ClearMemberWinners(groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearMemberWinners", reflect.TypeOf((*MockDuplicateRepository)(nil).ClearMemberWinners), groupID)
}

// CountPendingGroups mocks base method.
func (m *MockDuplicateRepository) CountPendingGroups() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingGroups")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingGroups indicates an expected call of CountPendingGroups.
func (mr *MockDuplicateRepositoryMockRecorder) CountPendingGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingGroups", reflect.TypeOf((*MockDuplicateRepository)(nil).CountPendingGroups))
}

// CreateGroup mocks base method.
func (m *MockDuplicateRepository) CreateGroup(group *data.DuplicateGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", group)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockDuplicateRepositoryMockRecorder) CreateGroup(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockDuplicateRepository)(nil).CreateGroup), group)
}

// DeleteGroup mocks base method.
func (m *MockDuplicateRepository) DeleteGroup(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockDuplicateRepositoryMockRecorder) DeleteGroup(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockDuplicateRepository)(nil).DeleteGroup), id)
}

// GetGroupByID mocks base method.
func (m *MockDuplicateRepository) GetGroupByID(id uint) (*data.DuplicateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", id)
	ret0, _ := ret[0].(*data.DuplicateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockDuplicateRepositoryMockRecorder) GetGroupByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockDuplicateRepository)(nil).GetGroupByID), id)
}

// GetGroupByIDWithMembers mocks base method.
func (m *MockDuplicateRepository) GetGroupByIDWithMembers(id uint) (*data.DuplicateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByIDWithMembers", id)
	ret0, _ := ret[0].(*data.DuplicateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByIDWithMembers indicates an expected call of GetGroupByIDWithMembers.
func (mr *MockDuplicateRepositoryMockRecorder) GetGroupByIDWithMembers(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByIDWithMembers", reflect.TypeOf((*MockDuplicateRepository)(nil).GetGroupByIDWithMembers), id)
}

// GetGroupForScene mocks base method.
func (m *MockDuplicateRepository) GetGroupForScene(sceneID uint) (*data.DuplicateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupForScene", sceneID)
	ret0, _ := ret[0].(*data.DuplicateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupForScene indicates an expected call of GetGroupForScene.
func (mr *MockDuplicateRepositoryMockRecorder) GetGroupForScene(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupForScene", reflect.TypeOf((*MockDuplicateRepository)(nil).GetGroupForScene), sceneID)
}

// GetMembersForGroup mocks base method.
func (m *MockDuplicateRepository) GetMembersForGroup(groupID uint) ([]data.DuplicateGroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembersForGroup", groupID)
	ret0, _ := ret[0].([]data.DuplicateGroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersForGroup indicates an expected call of GetMembersForGroup.
func (mr *MockDuplicateRepositoryMockRecorder) GetMembersForGroup(groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersForGroup", reflect.TypeOf((*MockDuplicateRepository)(nil).GetMembersForGroup), groupID)
}

// ListGroups mocks base method.
func (m *MockDuplicateRepository) ListGroups(page, limit int, status string) ([]data.DuplicateGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", page, limit, status)
	ret0, _ := ret[0].([]data.DuplicateGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockDuplicateRepositoryMockRecorder) ListGroups(page, limit, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockDuplicateRepository)(nil).ListGroups), page, limit, status)
}

// SetGroupWinner mocks base method.
func (m *MockDuplicateRepository) SetGroupWinner(id, winnerSceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGroupWinner", id, winnerSceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGroupWinner indicates an expected call of SetGroupWinner.
func (mr *MockDuplicateRepositoryMockRecorder) SetGroupWinner(id, winnerSceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGroupWinner", reflect.TypeOf((*MockDuplicateRepository)(nil).SetGroupWinner), id, winnerSceneID)
}

// SetMemberWinner mocks base method.
func (m *MockDuplicateRepository) SetMemberWinner(groupID, sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMemberWinner", groupID, sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMemberWinner indicates an expected call of SetMemberWinner.
func (mr *MockDuplicateRepositoryMockRecorder) SetMemberWinner(groupID, sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemberWinner", reflect.TypeOf((*MockDuplicateRepository)(nil).SetMemberWinner), groupID, sceneID)
}

// UpdateGroupStatus mocks base method.
func (m *MockDuplicateRepository) UpdateGroupStatus(id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroupStatus indicates an expected call of UpdateGroupStatus.
func (mr *MockDuplicateRepositoryMockRecorder) UpdateGroupStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupStatus", reflect.TypeOf((*MockDuplicateRepository)(nil).UpdateGroupStatus), id, status)
}
