// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: WatchHistoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_watch_history_repository.go -package=mocks goonhub/internal/data WatchHistoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWatchHistoryRepository is a mock of WatchHistoryRepository interface.
type MockWatchHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWatchHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockWatchHistoryRepositoryMockRecorder is the mock recorder for MockWatchHistoryRepository.
type MockWatchHistoryRepositoryMockRecorder struct {
	mock *MockWatchHistoryRepository
}

// NewMockWatchHistoryRepository creates a new mock instance.
func NewMockWatchHistoryRepository(ctrl *gomock.Controller) *MockWatchHistoryRepository {
	mock := &MockWatchHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockWatchHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchHistoryRepository) EXPECT() *MockWatchHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetLastWatch mocks base method.
func (m *MockWatchHistoryRepository) GetLastWatch(userID, videoID uint) (*data.UserVideoWatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastWatch", userID, videoID)
	ret0, _ := ret[0].(*data.UserVideoWatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastWatch indicates an expected call of GetLastWatch.
func (mr *MockWatchHistoryRepositoryMockRecorder) GetLastWatch(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastWatch", reflect.TypeOf((*MockWatchHistoryRepository)(nil).GetLastWatch), userID, videoID)
}

// ListUserHistory mocks base method.
func (m *MockWatchHistoryRepository) ListUserHistory(userID uint, page, limit int) ([]data.UserVideoWatch, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserHistory", userID, page, limit)
	ret0, _ := ret[0].([]data.UserVideoWatch)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserHistory indicates an expected call of ListUserHistory.
func (mr *MockWatchHistoryRepositoryMockRecorder) ListUserHistory(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserHistory", reflect.TypeOf((*MockWatchHistoryRepository)(nil).ListUserHistory), userID, page, limit)
}

// ListVideoWatches mocks base method.
func (m *MockWatchHistoryRepository) ListVideoWatches(userID, videoID uint, limit int) ([]data.UserVideoWatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideoWatches", userID, videoID, limit)
	ret0, _ := ret[0].([]data.UserVideoWatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideoWatches indicates an expected call of ListVideoWatches.
func (mr *MockWatchHistoryRepositoryMockRecorder) ListVideoWatches(userID, videoID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideoWatches", reflect.TypeOf((*MockWatchHistoryRepository)(nil).ListVideoWatches), userID, videoID, limit)
}

// RecordWatch mocks base method.
func (m *MockWatchHistoryRepository) RecordWatch(userID, videoID uint, duration, position int, completed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordWatch", userID, videoID, duration, position, completed)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordWatch indicates an expected call of RecordWatch.
func (mr *MockWatchHistoryRepositoryMockRecorder) RecordWatch(userID, videoID, duration, position, completed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordWatch", reflect.TypeOf((*MockWatchHistoryRepository)(nil).RecordWatch), userID, videoID, duration, position, completed)
}

// TryIncrementViewCount mocks base method.
func (m *MockWatchHistoryRepository) TryIncrementViewCount(userID, videoID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryIncrementViewCount", userID, videoID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryIncrementViewCount indicates an expected call of TryIncrementViewCount.
func (mr *MockWatchHistoryRepositoryMockRecorder) TryIncrementViewCount(userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryIncrementViewCount", reflect.TypeOf((*MockWatchHistoryRepository)(nil).TryIncrementViewCount), userID, videoID)
}
