// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: PermissionRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_permission_repository.go -package=mocks goonhub/internal/data PermissionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPermissionRepository) List() ([]data.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]data.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPermissionRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionRepository)(nil).List))
}

// SyncRolePermissions mocks base method.
func (m *MockPermissionRepository) SyncRolePermissions(roleID uint, permissionIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncRolePermissions", roleID, permissionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncRolePermissions indicates an expected call of SyncRolePermissions.
func (mr *MockPermissionRepositoryMockRecorder) SyncRolePermissions(roleID, permissionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncRolePermissions", reflect.TypeOf((*MockPermissionRepository)(nil).SyncRolePermissions), roleID, permissionIDs)
}
