// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: ActorInteractionRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_actor_interaction_repository.go -package=mocks goonhub/internal/data ActorInteractionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActorInteractionRepository is a mock of ActorInteractionRepository interface.
type MockActorInteractionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorInteractionRepositoryMockRecorder
	isgomock struct{}
}

// MockActorInteractionRepositoryMockRecorder is the mock recorder for MockActorInteractionRepository.
type MockActorInteractionRepositoryMockRecorder struct {
	mock *MockActorInteractionRepository
}

// NewMockActorInteractionRepository creates a new mock instance.
func NewMockActorInteractionRepository(ctrl *gomock.Controller) *MockActorInteractionRepository {
	mock := &MockActorInteractionRepository{ctrl: ctrl}
	mock.recorder = &MockActorInteractionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorInteractionRepository) EXPECT() *MockActorInteractionRepositoryMockRecorder {
	return m.recorder
}

// DeleteLike mocks base method.
func (m *MockActorInteractionRepository) DeleteLike(userID, actorID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLike", userID, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLike indicates an expected call of DeleteLike.
func (mr *MockActorInteractionRepositoryMockRecorder) DeleteLike(userID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLike", reflect.TypeOf((*MockActorInteractionRepository)(nil).DeleteLike), userID, actorID)
}

// DeleteRating mocks base method.
func (m *MockActorInteractionRepository) DeleteRating(userID, actorID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRating", userID, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRating indicates an expected call of DeleteRating.
func (mr *MockActorInteractionRepositoryMockRecorder) DeleteRating(userID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRating", reflect.TypeOf((*MockActorInteractionRepository)(nil).DeleteRating), userID, actorID)
}

// GetAllInteractions mocks base method.
func (m *MockActorInteractionRepository) GetAllInteractions(userID, actorID uint) (*data.ActorInteractions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInteractions", userID, actorID)
	ret0, _ := ret[0].(*data.ActorInteractions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInteractions indicates an expected call of GetAllInteractions.
func (mr *MockActorInteractionRepositoryMockRecorder) GetAllInteractions(userID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInteractions", reflect.TypeOf((*MockActorInteractionRepository)(nil).GetAllInteractions), userID, actorID)
}

// GetLikedActorIDs mocks base method.
func (m *MockActorInteractionRepository) GetLikedActorIDs(userID uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedActorIDs", userID)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikedActorIDs indicates an expected call of GetLikedActorIDs.
func (mr *MockActorInteractionRepositoryMockRecorder) GetLikedActorIDs(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedActorIDs", reflect.TypeOf((*MockActorInteractionRepository)(nil).GetLikedActorIDs), userID)
}

// GetRating mocks base method.
func (m *MockActorInteractionRepository) GetRating(userID, actorID uint) (*data.UserActorRating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", userID, actorID)
	ret0, _ := ret[0].(*data.UserActorRating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockActorInteractionRepositoryMockRecorder) GetRating(userID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockActorInteractionRepository)(nil).GetRating), userID, actorID)
}

// IsLiked mocks base method.
func (m *MockActorInteractionRepository) IsLiked(userID, actorID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", userID, actorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockActorInteractionRepositoryMockRecorder) IsLiked(userID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockActorInteractionRepository)(nil).IsLiked), userID, actorID)
}

// SetLike mocks base method.
func (m *MockActorInteractionRepository) SetLike(userID, actorID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLike", userID, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLike indicates an expected call of SetLike.
func (mr *MockActorInteractionRepositoryMockRecorder) SetLike(userID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLike", reflect.TypeOf((*MockActorInteractionRepository)(nil).SetLike), userID, actorID)
}

// UpsertRating mocks base method.
func (m *MockActorInteractionRepository) UpsertRating(userID, actorID uint, rating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRating", userID, actorID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRating indicates an expected call of UpsertRating.
func (mr *MockActorInteractionRepositoryMockRecorder) UpsertRating(userID, actorID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRating", reflect.TypeOf((*MockActorInteractionRepository)(nil).UpsertRating), userID, actorID, rating)
}
