// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: FingerprintRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_fingerprint_repository.go -package=mocks goonhub/internal/data FingerprintRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFingerprintRepository is a mock of FingerprintRepository interface.
type MockFingerprintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFingerprintRepositoryMockRecorder
	isgomock struct{}
}

// MockFingerprintRepositoryMockRecorder is the mock recorder for MockFingerprintRepository.
type MockFingerprintRepositoryMockRecorder struct {
	mock *MockFingerprintRepository
}

// NewMockFingerprintRepository creates a new mock instance.
func NewMockFingerprintRepository(ctrl *gomock.Controller) *MockFingerprintRepository {
	mock := &MockFingerprintRepository{ctrl: ctrl}
	mock.recorder = &MockFingerprintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFingerprintRepository) EXPECT() *MockFingerprintRepositoryMockRecorder {
	return m.recorder
}

// BulkInsert mocks base method.
func (m *MockFingerprintRepository) BulkInsert(fingerprints []data.SceneFingerprint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsert", fingerprints)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsert indicates an expected call of BulkInsert.
func (mr *MockFingerprintRepositoryMockRecorder) BulkInsert(fingerprints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsert", reflect.TypeOf((*MockFingerprintRepository)(nil).BulkInsert), fingerprints)
}

// DeleteBySceneID mocks base method.
func (m *MockFingerprintRepository) DeleteBySceneID(sceneID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySceneID", sceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySceneID indicates an expected call of DeleteBySceneID.
func (mr *MockFingerprintRepositoryMockRecorder) DeleteBySceneID(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySceneID", reflect.TypeOf((*MockFingerprintRepository)(nil).DeleteBySceneID), sceneID)
}

// GetAllHashValues mocks base method.
func (m *MockFingerprintRepository) GetAllHashValues() ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHashValues")
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHashValues indicates an expected call of GetAllHashValues.
func (mr *MockFingerprintRepositoryMockRecorder) GetAllHashValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHashValues", reflect.TypeOf((*MockFingerprintRepository)(nil).GetAllHashValues))
}

// GetBySceneID mocks base method.
func (m *MockFingerprintRepository) GetBySceneID(sceneID uint) ([]data.SceneFingerprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySceneID", sceneID)
	ret0, _ := ret[0].([]data.SceneFingerprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySceneID indicates an expected call of GetBySceneID.
func (mr *MockFingerprintRepositoryMockRecorder) GetBySceneID(sceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySceneID", reflect.TypeOf((*MockFingerprintRepository)(nil).GetBySceneID), sceneID)
}

// GetFingerprintedSceneIDs mocks base method.
func (m *MockFingerprintRepository) GetFingerprintedSceneIDs() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFingerprintedSceneIDs")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFingerprintedSceneIDs indicates an expected call of GetFingerprintedSceneIDs.
func (mr *MockFingerprintRepositoryMockRecorder) GetFingerprintedSceneIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFingerprintedSceneIDs", reflect.TypeOf((*MockFingerprintRepository)(nil).GetFingerprintedSceneIDs))
}
