// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: SearchConfigRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_search_config_repository.go -package=mocks goonhub/internal/data SearchConfigRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchConfigRepository is a mock of SearchConfigRepository interface.
type MockSearchConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSearchConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockSearchConfigRepositoryMockRecorder is the mock recorder for MockSearchConfigRepository.
type MockSearchConfigRepositoryMockRecorder struct {
	mock *MockSearchConfigRepository
}

// NewMockSearchConfigRepository creates a new mock instance.
func NewMockSearchConfigRepository(ctrl *gomock.Controller) *MockSearchConfigRepository {
	mock := &MockSearchConfigRepository{ctrl: ctrl}
	mock.recorder = &MockSearchConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchConfigRepository) EXPECT() *MockSearchConfigRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSearchConfigRepository) Get() (*data.SearchConfigRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*data.SearchConfigRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSearchConfigRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSearchConfigRepository)(nil).Get))
}

// Upsert mocks base method.
func (m *MockSearchConfigRepository) Upsert(record *data.SearchConfigRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSearchConfigRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSearchConfigRepository)(nil).Upsert), record)
}
