ALTER TABLE videos
  ADD COLUMN file_created_at TIMESTAMPTZ,
  ADD COLUMN description TEXT NOT NULL DEFAULT '',
  ADD COLUMN studio TEXT NOT NULL DEFAULT '',
  ADD COLUMN tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN actors TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN cover_image_path TEXT NOT NULL DEFAULT '',
  ADD COLUMN file_hash TEXT NOT NULL DEFAULT '',
  ADD COLUMN frame_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN bit_rate BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN video_codec TEXT NOT NULL DEFAULT '',
  ADD COLUMN audio_codec TEXT NOT NULL DEFAULT '';
